# PostgreSQL 18 tuning for small OLTP workload
# DB Version: 18
# OS Type: linux
# DB Type: oltp
# Total Memory (RAM): 1 GB
# CPUs num: 1
# Connections num: 20
# Data Storage: ssd
#
# WARNING:
# wal_compression = lz4 requires PostgreSQL to be compiled with --with-lz4.
# io_method = io_uring requires PostgreSQL to be compiled with --with-liburing.

listen_addresses = '*'

max_connections = 20
shared_buffers = 256MB
effective_cache_size = 768MB
maintenance_work_mem = 64MB
checkpoint_completion_target = 0.9
wal_buffers = 7864kB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200
work_mem = 9362kB
huge_pages = off
jit = off
wal_compression = lz4
io_method = io_uring
min_wal_size = 2GB
max_wal_size = 8GB
