{{ config(
    materialized='table',
    engine='MergeTree()',
    order_by='(trade_date, security_code)',
    partition_by='toYear(trade_date)'
) }}

with ma as (
    select
        security_code,
        trade_date,
        price_ma_3,
        lag(price_ma_3) over (partition by security_code order by trade_date) as prev_price_ma_3,
        price_ma_5,
        lag(price_ma_5) over (partition by security_code order by trade_date) as prev_price_ma_5,
        price_ma_6,
        lag(price_ma_6) over (partition by security_code order by trade_date) as prev_price_ma_6,
        price_ma_10,
        lag(price_ma_10) over (partition by security_code order by trade_date) as prev_price_ma_10,
        price_ma_12,
        lag(price_ma_12) over (partition by security_code order by trade_date) as prev_price_ma_12,
        price_ma_14,
        lag(price_ma_14) over (partition by security_code order by trade_date) as prev_price_ma_14,
        price_ma_20,
        lag(price_ma_20) over (partition by security_code order by trade_date) as prev_price_ma_20,
        price_ma_24,
        lag(price_ma_24) over (partition by security_code order by trade_date) as prev_price_ma_24,
        price_ma_28,
        lag(price_ma_28) over (partition by security_code order by trade_date) as prev_price_ma_28,
        price_ma_30,
        lag(price_ma_30) over (partition by security_code order by trade_date) as prev_price_ma_30,
        price_ma_57,
        lag(price_ma_57) over (partition by security_code order by trade_date) as prev_price_ma_57,
        price_ma_60,
        lag(price_ma_60) over (partition by security_code order by trade_date) as prev_price_ma_60,
        price_ma_114,
        lag(price_ma_114) over (partition by security_code order by trade_date) as prev_price_ma_114,
        price_ma_250,
        lag(price_ma_250) over (partition by security_code order by trade_date) as prev_price_ma_250,
        price_avg_ma_3_6_12_24,
        lag(price_avg_ma_3_6_12_24) over (partition by security_code order by trade_date) as prev_price_avg_ma_3_6_12_24,
        price_avg_ma_14_28_57_114,
        lag(price_avg_ma_14_28_57_114) over (partition by security_code order by trade_date) as prev_price_avg_ma_14_28_57_114,
        price_ema2_10,
        lag(price_ema2_10) over (partition by security_code order by trade_date) as prev_price_ema2_10
    from {{ ref('int_stock_ma_daily') }}
),

boll as (
    select
        security_code,
        trade_date,
        boll_mid_10_1p5,
        lag(boll_mid_10_1p5) over (partition by security_code order by trade_date) as prev_boll_mid_10_1p5,
        boll_upper_10_1p5,
        lag(boll_upper_10_1p5) over (partition by security_code order by trade_date) as prev_boll_upper_10_1p5,
        boll_lower_10_1p5,
        lag(boll_lower_10_1p5) over (partition by security_code order by trade_date) as prev_boll_lower_10_1p5,
        boll_mid_20_2,
        lag(boll_mid_20_2) over (partition by security_code order by trade_date) as prev_boll_mid_20_2,
        boll_upper_20_2,
        lag(boll_upper_20_2) over (partition by security_code order by trade_date) as prev_boll_upper_20_2,
        boll_lower_20_2,
        lag(boll_lower_20_2) over (partition by security_code order by trade_date) as prev_boll_lower_20_2,
        boll_mid_50_2p5,
        lag(boll_mid_50_2p5) over (partition by security_code order by trade_date) as prev_boll_mid_50_2p5,
        boll_upper_50_2p5,
        lag(boll_upper_50_2p5) over (partition by security_code order by trade_date) as prev_boll_upper_50_2p5,
        boll_lower_50_2p5,
        lag(boll_lower_50_2p5) over (partition by security_code order by trade_date) as prev_boll_lower_50_2p5
    from {{ ref('int_stock_boll_daily') }}
),

macd as (
    select
        security_code,
        trade_date,
        macd_dif,
        lag(macd_dif) over (partition by security_code order by trade_date) as prev_macd_dif,
        macd_dea,
        lag(macd_dea) over (partition by security_code order by trade_date) as prev_macd_dea,
        macd_histogram,
        lag(macd_histogram) over (partition by security_code order by trade_date) as prev_macd_histogram
    from {{ ref('int_stock_macd_daily') }}
)

select
    ma.security_code as security_code,
    ma.trade_date as trade_date,
    ma.price_ma_3 as price_ma_3,
    ma.prev_price_ma_3 as prev_price_ma_3,
    ma.price_ma_5 as price_ma_5,
    ma.prev_price_ma_5 as prev_price_ma_5,
    ma.price_ma_6 as price_ma_6,
    ma.prev_price_ma_6 as prev_price_ma_6,
    ma.price_ma_10 as price_ma_10,
    ma.prev_price_ma_10 as prev_price_ma_10,
    ma.price_ma_12 as price_ma_12,
    ma.prev_price_ma_12 as prev_price_ma_12,
    ma.price_ma_14 as price_ma_14,
    ma.prev_price_ma_14 as prev_price_ma_14,
    ma.price_ma_20 as price_ma_20,
    ma.prev_price_ma_20 as prev_price_ma_20,
    ma.price_ma_24 as price_ma_24,
    ma.prev_price_ma_24 as prev_price_ma_24,
    ma.price_ma_28 as price_ma_28,
    ma.prev_price_ma_28 as prev_price_ma_28,
    ma.price_ma_30 as price_ma_30,
    ma.prev_price_ma_30 as prev_price_ma_30,
    ma.price_ma_57 as price_ma_57,
    ma.prev_price_ma_57 as prev_price_ma_57,
    ma.price_ma_60 as price_ma_60,
    ma.prev_price_ma_60 as prev_price_ma_60,
    ma.price_ma_114 as price_ma_114,
    ma.prev_price_ma_114 as prev_price_ma_114,
    ma.price_ma_250 as price_ma_250,
    ma.prev_price_ma_250 as prev_price_ma_250,
    ma.price_avg_ma_3_6_12_24 as price_avg_ma_3_6_12_24,
    ma.prev_price_avg_ma_3_6_12_24 as prev_price_avg_ma_3_6_12_24,
    ma.price_avg_ma_14_28_57_114 as price_avg_ma_14_28_57_114,
    ma.prev_price_avg_ma_14_28_57_114 as prev_price_avg_ma_14_28_57_114,
    ma.price_ema2_10 as price_ema2_10,
    ma.prev_price_ema2_10 as prev_price_ema2_10,
    boll.boll_mid_10_1p5 as boll_mid_10_1p5,
    boll.prev_boll_mid_10_1p5 as prev_boll_mid_10_1p5,
    boll.boll_upper_10_1p5 as boll_upper_10_1p5,
    boll.prev_boll_upper_10_1p5 as prev_boll_upper_10_1p5,
    boll.boll_lower_10_1p5 as boll_lower_10_1p5,
    boll.prev_boll_lower_10_1p5 as prev_boll_lower_10_1p5,
    boll.boll_mid_20_2 as boll_mid_20_2,
    boll.prev_boll_mid_20_2 as prev_boll_mid_20_2,
    boll.boll_upper_20_2 as boll_upper_20_2,
    boll.prev_boll_upper_20_2 as prev_boll_upper_20_2,
    boll.boll_lower_20_2 as boll_lower_20_2,
    boll.prev_boll_lower_20_2 as prev_boll_lower_20_2,
    boll.boll_mid_50_2p5 as boll_mid_50_2p5,
    boll.prev_boll_mid_50_2p5 as prev_boll_mid_50_2p5,
    boll.boll_upper_50_2p5 as boll_upper_50_2p5,
    boll.prev_boll_upper_50_2p5 as prev_boll_upper_50_2p5,
    boll.boll_lower_50_2p5 as boll_lower_50_2p5,
    boll.prev_boll_lower_50_2p5 as prev_boll_lower_50_2p5,
    macd.macd_dif as macd_dif,
    macd.prev_macd_dif as prev_macd_dif,
    macd.macd_dea as macd_dea,
    macd.prev_macd_dea as prev_macd_dea,
    macd.macd_histogram as macd_histogram,
    macd.prev_macd_histogram as prev_macd_histogram
from ma
left any join boll
    on ma.security_code = boll.security_code
    and ma.trade_date = boll.trade_date
left any join macd
    on ma.security_code = macd.security_code
    and ma.trade_date = macd.trade_date
