with source as (
    select
        SECUCODE,
        SECURITY_CODE,
        SECURITY_NAME_ABBR,
        ORG_CODE,
        ORG_TYPE,
        REPORT_DATE,
        REPORT_TYPE,
        REPORT_DATE_NAME,
        SECURITY_TYPE_CODE,
        NOTICE_DATE,
        UPDATE_DATE,
        CURRENCY,
        SALES_SERVICES,
        DEPOSIT_INTERBANK_ADD,
        LOAN_PBC_ADD,
        OFI_BF_ADD,
        RECEIVE_ORIGIC_PREMIUM,
        RECEIVE_REINSURE_NET,
        INSURED_INVEST_ADD,
        DISPOSAL_TFA_ADD,
        RECEIVE_INTEREST_COMMISSION,
        BORROW_FUND_ADD,
        LOAN_ADVANCE_REDUCE,
        REPO_BUSINESS_ADD,
        RECEIVE_TAX_REFUND,
        RECEIVE_OTHER_OPERATE,
        OPERATE_INFLOW_OTHER,
        OPERATE_INFLOW_BALANCE,
        TOTAL_OPERATE_INFLOW,
        BUY_SERVICES,
        LOAN_ADVANCE_ADD,
        PBC_INTERBANK_ADD,
        PAY_ORIGIC_COMPENSATE,
        PAY_INTEREST_COMMISSION,
        PAY_POLICY_BONUS,
        PAY_STAFF_CASH,
        PAY_ALL_TAX,
        PAY_OTHER_OPERATE,
        OPERATE_OUTFLOW_OTHER,
        OPERATE_OUTFLOW_BALANCE,
        TOTAL_OPERATE_OUTFLOW,
        OPERATE_NETCASH_OTHER,
        OPERATE_NETCASH_BALANCE,
        NETCASH_OPERATE,
        WITHDRAW_INVEST,
        RECEIVE_INVEST_INCOME,
        DISPOSAL_LONG_ASSET,
        DISPOSAL_SUBSIDIARY_OTHER,
        REDUCE_PLEDGE_TIMEDEPOSITS,
        RECEIVE_OTHER_INVEST,
        INVEST_INFLOW_OTHER,
        INVEST_INFLOW_BALANCE,
        TOTAL_INVEST_INFLOW,
        CONSTRUCT_LONG_ASSET,
        INVEST_PAY_CASH,
        PLEDGE_LOAN_ADD,
        OBTAIN_SUBSIDIARY_OTHER,
        ADD_PLEDGE_TIMEDEPOSITS,
        PAY_OTHER_INVEST,
        INVEST_OUTFLOW_OTHER,
        INVEST_OUTFLOW_BALANCE,
        TOTAL_INVEST_OUTFLOW,
        INVEST_NETCASH_OTHER,
        INVEST_NETCASH_BALANCE,
        NETCASH_INVEST,
        ACCEPT_INVEST_CASH,
        SUBSIDIARY_ACCEPT_INVEST,
        RECEIVE_LOAN_CASH,
        ISSUE_BOND,
        RECEIVE_OTHER_FINANCE,
        FINANCE_INFLOW_OTHER,
        FINANCE_INFLOW_BALANCE,
        TOTAL_FINANCE_INFLOW,
        PAY_DEBT_CASH,
        ASSIGN_DIVIDEND_PORFIT,
        SUBSIDIARY_PAY_DIVIDEND,
        BUY_SUBSIDIARY_EQUITY,
        PAY_OTHER_FINANCE,
        SUBSIDIARY_REDUCE_CASH,
        FINANCE_OUTFLOW_OTHER,
        FINANCE_OUTFLOW_BALANCE,
        TOTAL_FINANCE_OUTFLOW,
        FINANCE_NETCASH_OTHER,
        FINANCE_NETCASH_BALANCE,
        NETCASH_FINANCE,
        RATE_CHANGE_EFFECT,
        CCE_ADD_OTHER,
        CCE_ADD_BALANCE,
        CCE_ADD,
        BEGIN_CCE,
        END_CCE_OTHER,
        END_CCE_BALANCE,
        END_CCE,
        NETPROFIT,
        ASSET_IMPAIRMENT,
        FA_IR_DEPR,
        OILGAS_BIOLOGY_DEPR,
        IR_DEPR,
        IA_AMORTIZE,
        LPE_AMORTIZE,
        DEFER_INCOME_AMORTIZE,
        PREPAID_EXPENSE_REDUCE,
        ACCRUED_EXPENSE_ADD,
        DISPOSAL_LONGASSET_LOSS,
        FA_SCRAP_LOSS,
        FAIRVALUE_CHANGE_LOSS,
        FINANCE_EXPENSE,
        INVEST_LOSS,
        DEFER_TAX,
        DT_ASSET_REDUCE,
        DT_LIAB_ADD,
        PREDICT_LIAB_ADD,
        INVENTORY_REDUCE,
        OPERATE_RECE_REDUCE,
        OPERATE_PAYABLE_ADD,
        OTHER,
        OPERATE_NETCASH_OTHERNOTE,
        OPERATE_NETCASH_BALANCENOTE,
        NETCASH_OPERATENOTE,
        DEBT_TRANSFER_CAPITAL,
        CONVERT_BOND_1YEAR,
        FINLEASE_OBTAIN_FA,
        UNINVOLVE_INVESTFIN_OTHER,
        END_CASH,
        BEGIN_CASH,
        END_CASH_EQUIVALENTS,
        BEGIN_CASH_EQUIVALENTS,
        CCE_ADD_OTHERNOTE,
        CCE_ADD_BALANCENOTE,
        CCE_ADDNOTE,
        SALES_SERVICES_YOY,
        DEPOSIT_INTERBANK_ADD_YOY,
        LOAN_PBC_ADD_YOY,
        OFI_BF_ADD_YOY,
        RECEIVE_ORIGIC_PREMIUM_YOY,
        RECEIVE_REINSURE_NET_YOY,
        INSURED_INVEST_ADD_YOY,
        DISPOSAL_TFA_ADD_YOY,
        RECEIVE_INTEREST_COMMISSION_YOY,
        BORROW_FUND_ADD_YOY,
        LOAN_ADVANCE_REDUCE_YOY,
        REPO_BUSINESS_ADD_YOY,
        RECEIVE_TAX_REFUND_YOY,
        RECEIVE_OTHER_OPERATE_YOY,
        OPERATE_INFLOW_OTHER_YOY,
        OPERATE_INFLOW_BALANCE_YOY,
        TOTAL_OPERATE_INFLOW_YOY,
        BUY_SERVICES_YOY,
        LOAN_ADVANCE_ADD_YOY,
        PBC_INTERBANK_ADD_YOY,
        PAY_ORIGIC_COMPENSATE_YOY,
        PAY_INTEREST_COMMISSION_YOY,
        PAY_POLICY_BONUS_YOY,
        PAY_STAFF_CASH_YOY,
        PAY_ALL_TAX_YOY,
        PAY_OTHER_OPERATE_YOY,
        OPERATE_OUTFLOW_OTHER_YOY,
        OPERATE_OUTFLOW_BALANCE_YOY,
        TOTAL_OPERATE_OUTFLOW_YOY,
        OPERATE_NETCASH_OTHER_YOY,
        OPERATE_NETCASH_BALANCE_YOY,
        NETCASH_OPERATE_YOY,
        WITHDRAW_INVEST_YOY,
        RECEIVE_INVEST_INCOME_YOY,
        DISPOSAL_LONG_ASSET_YOY,
        DISPOSAL_SUBSIDIARY_OTHER_YOY,
        REDUCE_PLEDGE_TIMEDEPOSITS_YOY,
        RECEIVE_OTHER_INVEST_YOY,
        INVEST_INFLOW_OTHER_YOY,
        INVEST_INFLOW_BALANCE_YOY,
        TOTAL_INVEST_INFLOW_YOY,
        CONSTRUCT_LONG_ASSET_YOY,
        INVEST_PAY_CASH_YOY,
        PLEDGE_LOAN_ADD_YOY,
        OBTAIN_SUBSIDIARY_OTHER_YOY,
        ADD_PLEDGE_TIMEDEPOSITS_YOY,
        PAY_OTHER_INVEST_YOY,
        INVEST_OUTFLOW_OTHER_YOY,
        INVEST_OUTFLOW_BALANCE_YOY,
        TOTAL_INVEST_OUTFLOW_YOY,
        INVEST_NETCASH_OTHER_YOY,
        INVEST_NETCASH_BALANCE_YOY,
        NETCASH_INVEST_YOY,
        ACCEPT_INVEST_CASH_YOY,
        SUBSIDIARY_ACCEPT_INVEST_YOY,
        RECEIVE_LOAN_CASH_YOY,
        ISSUE_BOND_YOY,
        RECEIVE_OTHER_FINANCE_YOY,
        FINANCE_INFLOW_OTHER_YOY,
        FINANCE_INFLOW_BALANCE_YOY,
        TOTAL_FINANCE_INFLOW_YOY,
        PAY_DEBT_CASH_YOY,
        ASSIGN_DIVIDEND_PORFIT_YOY,
        SUBSIDIARY_PAY_DIVIDEND_YOY,
        BUY_SUBSIDIARY_EQUITY_YOY,
        PAY_OTHER_FINANCE_YOY,
        SUBSIDIARY_REDUCE_CASH_YOY,
        FINANCE_OUTFLOW_OTHER_YOY,
        FINANCE_OUTFLOW_BALANCE_YOY,
        TOTAL_FINANCE_OUTFLOW_YOY,
        FINANCE_NETCASH_OTHER_YOY,
        FINANCE_NETCASH_BALANCE_YOY,
        NETCASH_FINANCE_YOY,
        RATE_CHANGE_EFFECT_YOY,
        CCE_ADD_OTHER_YOY,
        CCE_ADD_BALANCE_YOY,
        CCE_ADD_YOY,
        BEGIN_CCE_YOY,
        END_CCE_OTHER_YOY,
        END_CCE_BALANCE_YOY,
        END_CCE_YOY,
        NETPROFIT_YOY,
        ASSET_IMPAIRMENT_YOY,
        FA_IR_DEPR_YOY,
        OILGAS_BIOLOGY_DEPR_YOY,
        IR_DEPR_YOY,
        IA_AMORTIZE_YOY,
        LPE_AMORTIZE_YOY,
        DEFER_INCOME_AMORTIZE_YOY,
        PREPAID_EXPENSE_REDUCE_YOY,
        ACCRUED_EXPENSE_ADD_YOY,
        DISPOSAL_LONGASSET_LOSS_YOY,
        FA_SCRAP_LOSS_YOY,
        FAIRVALUE_CHANGE_LOSS_YOY,
        FINANCE_EXPENSE_YOY,
        INVEST_LOSS_YOY,
        DEFER_TAX_YOY,
        DT_ASSET_REDUCE_YOY,
        DT_LIAB_ADD_YOY,
        PREDICT_LIAB_ADD_YOY,
        INVENTORY_REDUCE_YOY,
        OPERATE_RECE_REDUCE_YOY,
        OPERATE_PAYABLE_ADD_YOY,
        OTHER_YOY,
        OPERATE_NETCASH_OTHERNOTE_YOY,
        OPERATE_NETCASH_BALANCENOTE_YOY,
        NETCASH_OPERATENOTE_YOY,
        DEBT_TRANSFER_CAPITAL_YOY,
        CONVERT_BOND_1YEAR_YOY,
        FINLEASE_OBTAIN_FA_YOY,
        UNINVOLVE_INVESTFIN_OTHER_YOY,
        END_CASH_YOY,
        BEGIN_CASH_YOY,
        END_CASH_EQUIVALENTS_YOY,
        BEGIN_CASH_EQUIVALENTS_YOY,
        CCE_ADD_OTHERNOTE_YOY,
        CCE_ADD_BALANCENOTE_YOY,
        CCE_ADDNOTE_YOY,
        OPINION_TYPE,
        OSOPINION_TYPE,
        MINORITY_INTEREST,
        MINORITY_INTEREST_YOY,
        USERIGHT_ASSET_AMORTIZE,
        USERIGHT_ASSET_AMORTIZE_YOY
    from {{ source('raw', 'eastmoney__cashflow_ytd') }}
)

select
    {{ normalize_cn_security_code('SECUCODE', input_format='eastmoney_suffix') }} as security_code,
    {{ cn_security_local_code('SECURITY_CODE', input_format='a_share_local_code') }} as security_local_code,
    SECURITY_NAME_ABBR as security_name_abbr,
    ORG_CODE as org_code,
    ORG_TYPE as org_type,
    REPORT_DATE as report_date,
    REPORT_TYPE as report_type,
    REPORT_DATE_NAME as report_date_name,
    SECURITY_TYPE_CODE as security_type_code,
    NOTICE_DATE as notice_date,
    UPDATE_DATE as update_date,
    CURRENCY as currency,
    SALES_SERVICES as sales_services,
    DEPOSIT_INTERBANK_ADD as deposit_interbank_add,
    LOAN_PBC_ADD as loan_pbc_add,
    OFI_BF_ADD as ofi_bf_add,
    RECEIVE_ORIGIC_PREMIUM as receive_origic_premium,
    RECEIVE_REINSURE_NET as receive_reinsure_net,
    INSURED_INVEST_ADD as insured_invest_add,
    DISPOSAL_TFA_ADD as disposal_tfa_add,
    RECEIVE_INTEREST_COMMISSION as receive_interest_commission,
    BORROW_FUND_ADD as borrow_fund_add,
    LOAN_ADVANCE_REDUCE as loan_advance_reduce,
    REPO_BUSINESS_ADD as repo_business_add,
    RECEIVE_TAX_REFUND as receive_tax_refund,
    RECEIVE_OTHER_OPERATE as receive_other_operate,
    OPERATE_INFLOW_OTHER as operate_inflow_other,
    OPERATE_INFLOW_BALANCE as operate_inflow_balance,
    TOTAL_OPERATE_INFLOW as total_operate_inflow,
    BUY_SERVICES as buy_services,
    LOAN_ADVANCE_ADD as loan_advance_add,
    PBC_INTERBANK_ADD as pbc_interbank_add,
    PAY_ORIGIC_COMPENSATE as pay_origic_compensate,
    PAY_INTEREST_COMMISSION as pay_interest_commission,
    PAY_POLICY_BONUS as pay_policy_bonus,
    PAY_STAFF_CASH as pay_staff_cash,
    PAY_ALL_TAX as pay_all_tax,
    PAY_OTHER_OPERATE as pay_other_operate,
    OPERATE_OUTFLOW_OTHER as operate_outflow_other,
    OPERATE_OUTFLOW_BALANCE as operate_outflow_balance,
    TOTAL_OPERATE_OUTFLOW as total_operate_outflow,
    OPERATE_NETCASH_OTHER as operate_netcash_other,
    OPERATE_NETCASH_BALANCE as operate_netcash_balance,
    NETCASH_OPERATE as netcash_operate,
    WITHDRAW_INVEST as withdraw_invest,
    RECEIVE_INVEST_INCOME as receive_invest_income,
    DISPOSAL_LONG_ASSET as disposal_long_asset,
    DISPOSAL_SUBSIDIARY_OTHER as disposal_subsidiary_other,
    REDUCE_PLEDGE_TIMEDEPOSITS as reduce_pledge_timedeposits,
    RECEIVE_OTHER_INVEST as receive_other_invest,
    INVEST_INFLOW_OTHER as invest_inflow_other,
    INVEST_INFLOW_BALANCE as invest_inflow_balance,
    TOTAL_INVEST_INFLOW as total_invest_inflow,
    CONSTRUCT_LONG_ASSET as construct_long_asset,
    INVEST_PAY_CASH as invest_pay_cash,
    PLEDGE_LOAN_ADD as pledge_loan_add,
    OBTAIN_SUBSIDIARY_OTHER as obtain_subsidiary_other,
    ADD_PLEDGE_TIMEDEPOSITS as add_pledge_timedeposits,
    PAY_OTHER_INVEST as pay_other_invest,
    INVEST_OUTFLOW_OTHER as invest_outflow_other,
    INVEST_OUTFLOW_BALANCE as invest_outflow_balance,
    TOTAL_INVEST_OUTFLOW as total_invest_outflow,
    INVEST_NETCASH_OTHER as invest_netcash_other,
    INVEST_NETCASH_BALANCE as invest_netcash_balance,
    NETCASH_INVEST as netcash_invest,
    ACCEPT_INVEST_CASH as accept_invest_cash,
    SUBSIDIARY_ACCEPT_INVEST as subsidiary_accept_invest,
    RECEIVE_LOAN_CASH as receive_loan_cash,
    ISSUE_BOND as issue_bond,
    RECEIVE_OTHER_FINANCE as receive_other_finance,
    FINANCE_INFLOW_OTHER as finance_inflow_other,
    FINANCE_INFLOW_BALANCE as finance_inflow_balance,
    TOTAL_FINANCE_INFLOW as total_finance_inflow,
    PAY_DEBT_CASH as pay_debt_cash,
    ASSIGN_DIVIDEND_PORFIT as assign_dividend_profit,
    SUBSIDIARY_PAY_DIVIDEND as subsidiary_pay_dividend,
    BUY_SUBSIDIARY_EQUITY as buy_subsidiary_equity,
    PAY_OTHER_FINANCE as pay_other_finance,
    SUBSIDIARY_REDUCE_CASH as subsidiary_reduce_cash,
    FINANCE_OUTFLOW_OTHER as finance_outflow_other,
    FINANCE_OUTFLOW_BALANCE as finance_outflow_balance,
    TOTAL_FINANCE_OUTFLOW as total_finance_outflow,
    FINANCE_NETCASH_OTHER as finance_netcash_other,
    FINANCE_NETCASH_BALANCE as finance_netcash_balance,
    NETCASH_FINANCE as netcash_finance,
    RATE_CHANGE_EFFECT as rate_change_effect,
    CCE_ADD_OTHER as cce_add_other,
    CCE_ADD_BALANCE as cce_add_balance,
    CCE_ADD as cce_add,
    BEGIN_CCE as begin_cce,
    END_CCE_OTHER as end_cce_other,
    END_CCE_BALANCE as end_cce_balance,
    END_CCE as end_cce,
    NETPROFIT as netprofit,
    ASSET_IMPAIRMENT as asset_impairment,
    FA_IR_DEPR as fa_ir_depr,
    OILGAS_BIOLOGY_DEPR as oilgas_biology_depr,
    IR_DEPR as ir_depr,
    IA_AMORTIZE as ia_amortize,
    LPE_AMORTIZE as lpe_amortize,
    DEFER_INCOME_AMORTIZE as defer_income_amortize,
    PREPAID_EXPENSE_REDUCE as prepaid_expense_reduce,
    ACCRUED_EXPENSE_ADD as accrued_expense_add,
    DISPOSAL_LONGASSET_LOSS as disposal_longasset_loss,
    FA_SCRAP_LOSS as fa_scrap_loss,
    FAIRVALUE_CHANGE_LOSS as fairvalue_change_loss,
    FINANCE_EXPENSE as finance_expense,
    INVEST_LOSS as invest_loss,
    DEFER_TAX as defer_tax,
    DT_ASSET_REDUCE as dt_asset_reduce,
    DT_LIAB_ADD as dt_liab_add,
    PREDICT_LIAB_ADD as predict_liab_add,
    INVENTORY_REDUCE as inventory_reduce,
    OPERATE_RECE_REDUCE as operate_rece_reduce,
    OPERATE_PAYABLE_ADD as operate_payable_add,
    OTHER as other,
    OPERATE_NETCASH_OTHERNOTE as operate_netcash_other_note,
    OPERATE_NETCASH_BALANCENOTE as operate_netcash_balance_note,
    NETCASH_OPERATENOTE as netcash_operate_note,
    DEBT_TRANSFER_CAPITAL as debt_transfer_capital,
    CONVERT_BOND_1YEAR as convert_bond_1year,
    FINLEASE_OBTAIN_FA as finlease_obtain_fa,
    UNINVOLVE_INVESTFIN_OTHER as uninvolve_investfin_other,
    END_CASH as end_cash,
    BEGIN_CASH as begin_cash,
    END_CASH_EQUIVALENTS as end_cash_equivalents,
    BEGIN_CASH_EQUIVALENTS as begin_cash_equivalents,
    CCE_ADD_OTHERNOTE as cce_add_other_note,
    CCE_ADD_BALANCENOTE as cce_add_balance_note,
    CCE_ADDNOTE as cce_add_note,
    SALES_SERVICES_YOY as sales_services_yoy,
    DEPOSIT_INTERBANK_ADD_YOY as deposit_interbank_add_yoy,
    LOAN_PBC_ADD_YOY as loan_pbc_add_yoy,
    OFI_BF_ADD_YOY as ofi_bf_add_yoy,
    RECEIVE_ORIGIC_PREMIUM_YOY as receive_origic_premium_yoy,
    RECEIVE_REINSURE_NET_YOY as receive_reinsure_net_yoy,
    INSURED_INVEST_ADD_YOY as insured_invest_add_yoy,
    DISPOSAL_TFA_ADD_YOY as disposal_tfa_add_yoy,
    RECEIVE_INTEREST_COMMISSION_YOY as receive_interest_commission_yoy,
    BORROW_FUND_ADD_YOY as borrow_fund_add_yoy,
    LOAN_ADVANCE_REDUCE_YOY as loan_advance_reduce_yoy,
    REPO_BUSINESS_ADD_YOY as repo_business_add_yoy,
    RECEIVE_TAX_REFUND_YOY as receive_tax_refund_yoy,
    RECEIVE_OTHER_OPERATE_YOY as receive_other_operate_yoy,
    OPERATE_INFLOW_OTHER_YOY as operate_inflow_other_yoy,
    OPERATE_INFLOW_BALANCE_YOY as operate_inflow_balance_yoy,
    TOTAL_OPERATE_INFLOW_YOY as total_operate_inflow_yoy,
    BUY_SERVICES_YOY as buy_services_yoy,
    LOAN_ADVANCE_ADD_YOY as loan_advance_add_yoy,
    PBC_INTERBANK_ADD_YOY as pbc_interbank_add_yoy,
    PAY_ORIGIC_COMPENSATE_YOY as pay_origic_compensate_yoy,
    PAY_INTEREST_COMMISSION_YOY as pay_interest_commission_yoy,
    PAY_POLICY_BONUS_YOY as pay_policy_bonus_yoy,
    PAY_STAFF_CASH_YOY as pay_staff_cash_yoy,
    PAY_ALL_TAX_YOY as pay_all_tax_yoy,
    PAY_OTHER_OPERATE_YOY as pay_other_operate_yoy,
    OPERATE_OUTFLOW_OTHER_YOY as operate_outflow_other_yoy,
    OPERATE_OUTFLOW_BALANCE_YOY as operate_outflow_balance_yoy,
    TOTAL_OPERATE_OUTFLOW_YOY as total_operate_outflow_yoy,
    OPERATE_NETCASH_OTHER_YOY as operate_netcash_other_yoy,
    OPERATE_NETCASH_BALANCE_YOY as operate_netcash_balance_yoy,
    NETCASH_OPERATE_YOY as netcash_operate_yoy,
    WITHDRAW_INVEST_YOY as withdraw_invest_yoy,
    RECEIVE_INVEST_INCOME_YOY as receive_invest_income_yoy,
    DISPOSAL_LONG_ASSET_YOY as disposal_long_asset_yoy,
    DISPOSAL_SUBSIDIARY_OTHER_YOY as disposal_subsidiary_other_yoy,
    REDUCE_PLEDGE_TIMEDEPOSITS_YOY as reduce_pledge_timedeposits_yoy,
    RECEIVE_OTHER_INVEST_YOY as receive_other_invest_yoy,
    INVEST_INFLOW_OTHER_YOY as invest_inflow_other_yoy,
    INVEST_INFLOW_BALANCE_YOY as invest_inflow_balance_yoy,
    TOTAL_INVEST_INFLOW_YOY as total_invest_inflow_yoy,
    CONSTRUCT_LONG_ASSET_YOY as construct_long_asset_yoy,
    INVEST_PAY_CASH_YOY as invest_pay_cash_yoy,
    PLEDGE_LOAN_ADD_YOY as pledge_loan_add_yoy,
    OBTAIN_SUBSIDIARY_OTHER_YOY as obtain_subsidiary_other_yoy,
    ADD_PLEDGE_TIMEDEPOSITS_YOY as add_pledge_timedeposits_yoy,
    PAY_OTHER_INVEST_YOY as pay_other_invest_yoy,
    INVEST_OUTFLOW_OTHER_YOY as invest_outflow_other_yoy,
    INVEST_OUTFLOW_BALANCE_YOY as invest_outflow_balance_yoy,
    TOTAL_INVEST_OUTFLOW_YOY as total_invest_outflow_yoy,
    INVEST_NETCASH_OTHER_YOY as invest_netcash_other_yoy,
    INVEST_NETCASH_BALANCE_YOY as invest_netcash_balance_yoy,
    NETCASH_INVEST_YOY as netcash_invest_yoy,
    ACCEPT_INVEST_CASH_YOY as accept_invest_cash_yoy,
    SUBSIDIARY_ACCEPT_INVEST_YOY as subsidiary_accept_invest_yoy,
    RECEIVE_LOAN_CASH_YOY as receive_loan_cash_yoy,
    ISSUE_BOND_YOY as issue_bond_yoy,
    RECEIVE_OTHER_FINANCE_YOY as receive_other_finance_yoy,
    FINANCE_INFLOW_OTHER_YOY as finance_inflow_other_yoy,
    FINANCE_INFLOW_BALANCE_YOY as finance_inflow_balance_yoy,
    TOTAL_FINANCE_INFLOW_YOY as total_finance_inflow_yoy,
    PAY_DEBT_CASH_YOY as pay_debt_cash_yoy,
    ASSIGN_DIVIDEND_PORFIT_YOY as assign_dividend_profit_yoy,
    SUBSIDIARY_PAY_DIVIDEND_YOY as subsidiary_pay_dividend_yoy,
    BUY_SUBSIDIARY_EQUITY_YOY as buy_subsidiary_equity_yoy,
    PAY_OTHER_FINANCE_YOY as pay_other_finance_yoy,
    SUBSIDIARY_REDUCE_CASH_YOY as subsidiary_reduce_cash_yoy,
    FINANCE_OUTFLOW_OTHER_YOY as finance_outflow_other_yoy,
    FINANCE_OUTFLOW_BALANCE_YOY as finance_outflow_balance_yoy,
    TOTAL_FINANCE_OUTFLOW_YOY as total_finance_outflow_yoy,
    FINANCE_NETCASH_OTHER_YOY as finance_netcash_other_yoy,
    FINANCE_NETCASH_BALANCE_YOY as finance_netcash_balance_yoy,
    NETCASH_FINANCE_YOY as netcash_finance_yoy,
    RATE_CHANGE_EFFECT_YOY as rate_change_effect_yoy,
    CCE_ADD_OTHER_YOY as cce_add_other_yoy,
    CCE_ADD_BALANCE_YOY as cce_add_balance_yoy,
    CCE_ADD_YOY as cce_add_yoy,
    BEGIN_CCE_YOY as begin_cce_yoy,
    END_CCE_OTHER_YOY as end_cce_other_yoy,
    END_CCE_BALANCE_YOY as end_cce_balance_yoy,
    END_CCE_YOY as end_cce_yoy,
    NETPROFIT_YOY as netprofit_yoy,
    ASSET_IMPAIRMENT_YOY as asset_impairment_yoy,
    FA_IR_DEPR_YOY as fa_ir_depr_yoy,
    OILGAS_BIOLOGY_DEPR_YOY as oilgas_biology_depr_yoy,
    IR_DEPR_YOY as ir_depr_yoy,
    IA_AMORTIZE_YOY as ia_amortize_yoy,
    LPE_AMORTIZE_YOY as lpe_amortize_yoy,
    DEFER_INCOME_AMORTIZE_YOY as defer_income_amortize_yoy,
    PREPAID_EXPENSE_REDUCE_YOY as prepaid_expense_reduce_yoy,
    ACCRUED_EXPENSE_ADD_YOY as accrued_expense_add_yoy,
    DISPOSAL_LONGASSET_LOSS_YOY as disposal_longasset_loss_yoy,
    FA_SCRAP_LOSS_YOY as fa_scrap_loss_yoy,
    FAIRVALUE_CHANGE_LOSS_YOY as fairvalue_change_loss_yoy,
    FINANCE_EXPENSE_YOY as finance_expense_yoy,
    INVEST_LOSS_YOY as invest_loss_yoy,
    DEFER_TAX_YOY as defer_tax_yoy,
    DT_ASSET_REDUCE_YOY as dt_asset_reduce_yoy,
    DT_LIAB_ADD_YOY as dt_liab_add_yoy,
    PREDICT_LIAB_ADD_YOY as predict_liab_add_yoy,
    INVENTORY_REDUCE_YOY as inventory_reduce_yoy,
    OPERATE_RECE_REDUCE_YOY as operate_rece_reduce_yoy,
    OPERATE_PAYABLE_ADD_YOY as operate_payable_add_yoy,
    OTHER_YOY as other_yoy,
    OPERATE_NETCASH_OTHERNOTE_YOY as operate_netcash_other_note_yoy,
    OPERATE_NETCASH_BALANCENOTE_YOY as operate_netcash_balance_note_yoy,
    NETCASH_OPERATENOTE_YOY as netcash_operate_note_yoy,
    DEBT_TRANSFER_CAPITAL_YOY as debt_transfer_capital_yoy,
    CONVERT_BOND_1YEAR_YOY as convert_bond_1year_yoy,
    FINLEASE_OBTAIN_FA_YOY as finlease_obtain_fa_yoy,
    UNINVOLVE_INVESTFIN_OTHER_YOY as uninvolve_investfin_other_yoy,
    END_CASH_YOY as end_cash_yoy,
    BEGIN_CASH_YOY as begin_cash_yoy,
    END_CASH_EQUIVALENTS_YOY as end_cash_equivalents_yoy,
    BEGIN_CASH_EQUIVALENTS_YOY as begin_cash_equivalents_yoy,
    CCE_ADD_OTHERNOTE_YOY as cce_add_other_note_yoy,
    CCE_ADD_BALANCENOTE_YOY as cce_add_balance_note_yoy,
    CCE_ADDNOTE_YOY as cce_add_note_yoy,
    OPINION_TYPE as opinion_type,
    OSOPINION_TYPE as osopinion_type,
    MINORITY_INTEREST as minority_interest,
    MINORITY_INTEREST_YOY as minority_interest_yoy,
    USERIGHT_ASSET_AMORTIZE as use_right_asset_amortize,
    USERIGHT_ASSET_AMORTIZE_YOY as use_right_asset_amortize_yoy
from source
