with source as (
    select
        SECUCODE,
        SECURITY_CODE,
        ORG_CODE,
        END_DATE,
        CHANGE_REASON,
        LIMITED_SHARES,
        UNLIMITED_SHARES,
        TOTAL_SHARES,
        LIMITED_SHARES_RATIO,
        LISTED_SHARES_RATIO,
        TOTAL_SHARES_RATIO,
        LISTED_A_SHARES,
        LIMITED_A_SHARES,
        LISTED_A_SHARES_RATIO,
        LIMITED_A_SHARES_RATIO,
        B_FREE_SHARE,
        H_FREE_SHARE,
        B_FREE_SHARE_RATIO,
        H_FREE_SHARE_RATIO,
        SECURITY_TYPE_CODE,
        NON_FREE_SHARES,
        NON_FREESHARES_RATIO,
        LIMITED_B_SHARES,
        LIMITED_BSHARES_RATIO,
        OTHER_FREE_SHARES,
        OTHER_FREESHARES_RATIO,
        LIMITED_STATE_SHARES,
        LIMITED_STATE_LEGAL,
        LIMITED_OTHARS,
        LIMITED_DOMESTIC_NOSTATE,
        LIMITED_DOMESTIC_NATURAL,
        LOCK_SHARES,
        LIMITED_FOREIGN_SHARES,
        LIMITED_OVERSEAS_NOSTATE,
        LIMITED_OVERSEAS_NATURAL,
        LIMITED_H_SHARES,
        SPONSOR_SHARES,
        STATE_SPONSOR_SHARES,
        SPONSOR_SOCIAL_SHARES,
        RAISE_SHARES,
        RAISE_STATE_SHARES,
        RAISE_DOMESTIC_SHARES,
        RAISE_OVERSEAS_SHARES,
        NOTICE_DATE,
        LISTING_DATE,
        LIMITED_SHARES_CHANGE,
        UNLIMITED_SHARES_CHANGE,
        TOTAL_SHARES_CHANGE,
        LISTED_ASHARES_CHANGE,
        LIMITED_ASHARES_CHANGE,
        B_FREESHARE_CHANGE,
        H_FREESHARE_CHANGE,
        LIMITED_BSHARES_CHANGE,
        NONFREE_SHARES_CHANGE,
        OTHERFREE_SHARES_CHANGE,
        FREE_SHARES,
        CHANGE_REASON_EXPLAIN,
        LIMITED_H_SHARES_RATIO,
        LIMITED_H_SHARES_CHANGE,
        IS_FREE_WINDOW,
        IS_LIMITED_WINDOW,
        LISTED_A_RATIOPC,
        LISTED_B_RATIOPC,
        LISTED_H_RATIOPC,
        LISTED_OTHER_RATIOPC,
        LISTED_SUM_RATIOPC,
        MARKET_CODE,
        IS_USE,
        SECURITY_NAME_ABBR
    from {{ source('raw', 'eastmoney__equity_history') }}
)

select
    {{ normalize_cn_security_code('SECUCODE', input_format='eastmoney_suffix') }} as security_code,
    {{ cn_security_local_code('SECURITY_CODE', input_format='a_share_local_code') }} as security_local_code,
    ORG_CODE as org_code,
    END_DATE as report_date,
    CHANGE_REASON as change_reason,
    LIMITED_SHARES as limited_shares,
    UNLIMITED_SHARES as unlimited_shares,
    TOTAL_SHARES as total_shares,
    LIMITED_SHARES_RATIO as limited_shares_ratio,
    LISTED_SHARES_RATIO as listed_shares_ratio,
    TOTAL_SHARES_RATIO as total_shares_ratio,
    LISTED_A_SHARES as listed_a_shares,
    LIMITED_A_SHARES as limited_a_shares,
    LISTED_A_SHARES_RATIO as listed_a_shares_ratio,
    LIMITED_A_SHARES_RATIO as limited_a_shares_ratio,
    B_FREE_SHARE as b_free_share,
    H_FREE_SHARE as h_free_share,
    B_FREE_SHARE_RATIO as b_free_share_ratio,
    H_FREE_SHARE_RATIO as h_free_share_ratio,
    SECURITY_TYPE_CODE as security_type_code,
    NON_FREE_SHARES as non_free_shares,
    NON_FREESHARES_RATIO as non_free_shares_ratio,
    LIMITED_B_SHARES as limited_b_shares,
    LIMITED_BSHARES_RATIO as limited_b_shares_ratio,
    OTHER_FREE_SHARES as other_free_shares,
    OTHER_FREESHARES_RATIO as other_free_shares_ratio,
    LIMITED_STATE_SHARES as limited_state_shares,
    LIMITED_STATE_LEGAL as limited_state_legal,
    LIMITED_OTHARS as limited_othars,
    LIMITED_DOMESTIC_NOSTATE as limited_domestic_nostate,
    LIMITED_DOMESTIC_NATURAL as limited_domestic_natural,
    LOCK_SHARES as lock_shares,
    LIMITED_FOREIGN_SHARES as limited_foreign_shares,
    LIMITED_OVERSEAS_NOSTATE as limited_overseas_nostate,
    LIMITED_OVERSEAS_NATURAL as limited_overseas_natural,
    LIMITED_H_SHARES as limited_h_shares,
    SPONSOR_SHARES as sponsor_shares,
    STATE_SPONSOR_SHARES as state_sponsor_shares,
    SPONSOR_SOCIAL_SHARES as sponsor_social_shares,
    RAISE_SHARES as raise_shares,
    RAISE_STATE_SHARES as raise_state_shares,
    RAISE_DOMESTIC_SHARES as raise_domestic_shares,
    RAISE_OVERSEAS_SHARES as raise_overseas_shares,
    NOTICE_DATE as notice_date,
    LISTING_DATE as listing_date,
    LIMITED_SHARES_CHANGE as limited_shares_change,
    UNLIMITED_SHARES_CHANGE as unlimited_shares_change,
    TOTAL_SHARES_CHANGE as total_shares_change,
    LISTED_ASHARES_CHANGE as listed_a_shares_change,
    LIMITED_ASHARES_CHANGE as limited_a_shares_change,
    B_FREESHARE_CHANGE as b_free_share_change,
    H_FREESHARE_CHANGE as h_free_share_change,
    LIMITED_BSHARES_CHANGE as limited_b_shares_change,
    NONFREE_SHARES_CHANGE as non_free_shares_change,
    OTHERFREE_SHARES_CHANGE as other_free_shares_change,
    FREE_SHARES as free_shares,
    CHANGE_REASON_EXPLAIN as change_reason_explain,
    LIMITED_H_SHARES_RATIO as limited_h_shares_ratio,
    LIMITED_H_SHARES_CHANGE as limited_h_shares_change,
    IS_FREE_WINDOW as is_free_window,
    IS_LIMITED_WINDOW as is_limited_window,
    LISTED_A_RATIOPC as listed_a_ratio_pc,
    LISTED_B_RATIOPC as listed_b_ratio_pc,
    LISTED_H_RATIOPC as listed_h_ratio_pc,
    LISTED_OTHER_RATIOPC as listed_other_ratio_pc,
    LISTED_SUM_RATIOPC as listed_sum_ratio_pc,
    MARKET_CODE as market_code,
    IS_USE as is_use,
    SECURITY_NAME_ABBR as security_name_abbr
from source
