with source as (
    select
        SECUCODE,
        SECURITY_CODE,
        SECURITY_NAME_ABBR,
        ORG_CODE,
        ORG_TYPE,
        REPORT_DATE,
        REPORT_TYPE,
        REPORT_DATE_NAME,
        SECURITY_TYPE_CODE,
        NOTICE_DATE,
        UPDATE_DATE,
        CURRENCY,
        TOTAL_OPERATE_INCOME,
        TOTAL_OPERATE_INCOME_YOY,
        OPERATE_INCOME,
        OPERATE_INCOME_YOY,
        INTEREST_INCOME,
        INTEREST_INCOME_YOY,
        EARNED_PREMIUM,
        EARNED_PREMIUM_YOY,
        FEE_COMMISSION_INCOME,
        FEE_COMMISSION_INCOME_YOY,
        OTHER_BUSINESS_INCOME,
        OTHER_BUSINESS_INCOME_YOY,
        TOI_OTHER,
        TOI_OTHER_YOY,
        TOTAL_OPERATE_COST,
        TOTAL_OPERATE_COST_YOY,
        OPERATE_COST,
        OPERATE_COST_YOY,
        INTEREST_EXPENSE,
        INTEREST_EXPENSE_YOY,
        FEE_COMMISSION_EXPENSE,
        FEE_COMMISSION_EXPENSE_YOY,
        RESEARCH_EXPENSE,
        RESEARCH_EXPENSE_YOY,
        SURRENDER_VALUE,
        SURRENDER_VALUE_YOY,
        NET_COMPENSATE_EXPENSE,
        NET_COMPENSATE_EXPENSE_YOY,
        NET_CONTRACT_RESERVE,
        NET_CONTRACT_RESERVE_YOY,
        POLICY_BONUS_EXPENSE,
        POLICY_BONUS_EXPENSE_YOY,
        REINSURE_EXPENSE,
        REINSURE_EXPENSE_YOY,
        OTHER_BUSINESS_COST,
        OTHER_BUSINESS_COST_YOY,
        OPERATE_TAX_ADD,
        OPERATE_TAX_ADD_YOY,
        SALE_EXPENSE,
        SALE_EXPENSE_YOY,
        MANAGE_EXPENSE,
        MANAGE_EXPENSE_YOY,
        ME_RESEARCH_EXPENSE,
        ME_RESEARCH_EXPENSE_YOY,
        FINANCE_EXPENSE,
        FINANCE_EXPENSE_YOY,
        FE_INTEREST_EXPENSE,
        FE_INTEREST_EXPENSE_YOY,
        FE_INTEREST_INCOME,
        FE_INTEREST_INCOME_YOY,
        ASSET_IMPAIRMENT_LOSS,
        ASSET_IMPAIRMENT_LOSS_YOY,
        CREDIT_IMPAIRMENT_LOSS,
        CREDIT_IMPAIRMENT_LOSS_YOY,
        TOC_OTHER,
        TOC_OTHER_YOY,
        FAIRVALUE_CHANGE_INCOME,
        FAIRVALUE_CHANGE_INCOME_YOY,
        INVEST_INCOME,
        INVEST_INCOME_YOY,
        INVEST_JOINT_INCOME,
        INVEST_JOINT_INCOME_YOY,
        NET_EXPOSURE_INCOME,
        NET_EXPOSURE_INCOME_YOY,
        EXCHANGE_INCOME,
        EXCHANGE_INCOME_YOY,
        ASSET_DISPOSAL_INCOME,
        ASSET_DISPOSAL_INCOME_YOY,
        ASSET_IMPAIRMENT_INCOME,
        ASSET_IMPAIRMENT_INCOME_YOY,
        CREDIT_IMPAIRMENT_INCOME,
        CREDIT_IMPAIRMENT_INCOME_YOY,
        OTHER_INCOME,
        OTHER_INCOME_YOY,
        OPERATE_PROFIT_OTHER,
        OPERATE_PROFIT_OTHER_YOY,
        OPERATE_PROFIT_BALANCE,
        OPERATE_PROFIT_BALANCE_YOY,
        OPERATE_PROFIT,
        OPERATE_PROFIT_YOY,
        NONBUSINESS_INCOME,
        NONBUSINESS_INCOME_YOY,
        NONCURRENT_DISPOSAL_INCOME,
        NONCURRENT_DISPOSAL_INCOME_YOY,
        NONBUSINESS_EXPENSE,
        NONBUSINESS_EXPENSE_YOY,
        NONCURRENT_DISPOSAL_LOSS,
        NONCURRENT_DISPOSAL_LOSS_YOY,
        EFFECT_TP_OTHER,
        EFFECT_TP_OTHER_YOY,
        TOTAL_PROFIT_BALANCE,
        TOTAL_PROFIT_BALANCE_YOY,
        TOTAL_PROFIT,
        TOTAL_PROFIT_YOY,
        INCOME_TAX,
        INCOME_TAX_YOY,
        EFFECT_NETPROFIT_OTHER,
        EFFECT_NETPROFIT_OTHER_YOY,
        EFFECT_NETPROFIT_BALANCE,
        EFFECT_NETPROFIT_BALANCE_YOY,
        UNCONFIRM_INVEST_LOSS,
        UNCONFIRM_INVEST_LOSS_YOY,
        NETPROFIT,
        NETPROFIT_YOY,
        PRECOMBINE_PROFIT,
        PRECOMBINE_PROFIT_YOY,
        CONTINUED_NETPROFIT,
        CONTINUED_NETPROFIT_YOY,
        DISCONTINUED_NETPROFIT,
        DISCONTINUED_NETPROFIT_YOY,
        PARENT_NETPROFIT,
        PARENT_NETPROFIT_YOY,
        MINORITY_INTEREST,
        MINORITY_INTEREST_YOY,
        DEDUCT_PARENT_NETPROFIT,
        DEDUCT_PARENT_NETPROFIT_YOY,
        NETPROFIT_OTHER,
        NETPROFIT_OTHER_YOY,
        NETPROFIT_BALANCE,
        NETPROFIT_BALANCE_YOY,
        BASIC_EPS,
        BASIC_EPS_YOY,
        DILUTED_EPS,
        DILUTED_EPS_YOY,
        OTHER_COMPRE_INCOME,
        OTHER_COMPRE_INCOME_YOY,
        PARENT_OCI,
        PARENT_OCI_YOY,
        MINORITY_OCI,
        MINORITY_OCI_YOY,
        PARENT_OCI_OTHER,
        PARENT_OCI_OTHER_YOY,
        PARENT_OCI_BALANCE,
        PARENT_OCI_BALANCE_YOY,
        UNABLE_OCI,
        UNABLE_OCI_YOY,
        CREDITRISK_FAIRVALUE_CHANGE,
        CREDITRISK_FAIRVALUE_CHANGE_YOY,
        OTHERRIGHT_FAIRVALUE_CHANGE,
        OTHERRIGHT_FAIRVALUE_CHANGE_YOY,
        SETUP_PROFIT_CHANGE,
        SETUP_PROFIT_CHANGE_YOY,
        RIGHTLAW_UNABLE_OCI,
        RIGHTLAW_UNABLE_OCI_YOY,
        UNABLE_OCI_OTHER,
        UNABLE_OCI_OTHER_YOY,
        UNABLE_OCI_BALANCE,
        UNABLE_OCI_BALANCE_YOY,
        ABLE_OCI,
        ABLE_OCI_YOY,
        RIGHTLAW_ABLE_OCI,
        RIGHTLAW_ABLE_OCI_YOY,
        AFA_FAIRVALUE_CHANGE,
        AFA_FAIRVALUE_CHANGE_YOY,
        HMI_AFA,
        HMI_AFA_YOY,
        CASHFLOW_HEDGE_VALID,
        CASHFLOW_HEDGE_VALID_YOY,
        CREDITOR_FAIRVALUE_CHANGE,
        CREDITOR_FAIRVALUE_CHANGE_YOY,
        CREDITOR_IMPAIRMENT_RESERVE,
        CREDITOR_IMPAIRMENT_RESERVE_YOY,
        FINANCE_OCI_AMT,
        FINANCE_OCI_AMT_YOY,
        CONVERT_DIFF,
        CONVERT_DIFF_YOY,
        ABLE_OCI_OTHER,
        ABLE_OCI_OTHER_YOY,
        ABLE_OCI_BALANCE,
        ABLE_OCI_BALANCE_YOY,
        OCI_OTHER,
        OCI_OTHER_YOY,
        OCI_BALANCE,
        OCI_BALANCE_YOY,
        TOTAL_COMPRE_INCOME,
        TOTAL_COMPRE_INCOME_YOY,
        PARENT_TCI,
        PARENT_TCI_YOY,
        MINORITY_TCI,
        MINORITY_TCI_YOY,
        PRECOMBINE_TCI,
        PRECOMBINE_TCI_YOY,
        EFFECT_TCI_BALANCE,
        EFFECT_TCI_BALANCE_YOY,
        TCI_OTHER,
        TCI_OTHER_YOY,
        TCI_BALANCE,
        TCI_BALANCE_YOY,
        ACF_END_INCOME,
        ACF_END_INCOME_YOY,
        OPINION_TYPE
    from {{ source('raw', 'eastmoney__income_ytd') }}
)

select
    {{ normalize_cn_security_code('SECUCODE', input_format='eastmoney_suffix') }} as security_code,
    {{ cn_security_local_code('SECURITY_CODE', input_format='a_share_local_code') }} as security_local_code,
    SECURITY_NAME_ABBR as security_name_abbr,
    ORG_CODE as org_code,
    ORG_TYPE as org_type,
    REPORT_DATE as report_date,
    REPORT_TYPE as report_type,
    REPORT_DATE_NAME as report_date_name,
    SECURITY_TYPE_CODE as security_type_code,
    NOTICE_DATE as notice_date,
    UPDATE_DATE as update_date,
    CURRENCY as currency,
    TOTAL_OPERATE_INCOME as total_operate_income,
    TOTAL_OPERATE_INCOME_YOY as total_operate_income_yoy,
    OPERATE_INCOME as operate_income,
    OPERATE_INCOME_YOY as operate_income_yoy,
    INTEREST_INCOME as interest_income,
    INTEREST_INCOME_YOY as interest_income_yoy,
    EARNED_PREMIUM as earned_premium,
    EARNED_PREMIUM_YOY as earned_premium_yoy,
    FEE_COMMISSION_INCOME as fee_commission_income,
    FEE_COMMISSION_INCOME_YOY as fee_commission_income_yoy,
    OTHER_BUSINESS_INCOME as other_business_income,
    OTHER_BUSINESS_INCOME_YOY as other_business_income_yoy,
    TOI_OTHER as toi_other,
    TOI_OTHER_YOY as toi_other_yoy,
    TOTAL_OPERATE_COST as total_operate_cost,
    TOTAL_OPERATE_COST_YOY as total_operate_cost_yoy,
    OPERATE_COST as operate_cost,
    OPERATE_COST_YOY as operate_cost_yoy,
    INTEREST_EXPENSE as interest_expense,
    INTEREST_EXPENSE_YOY as interest_expense_yoy,
    FEE_COMMISSION_EXPENSE as fee_commission_expense,
    FEE_COMMISSION_EXPENSE_YOY as fee_commission_expense_yoy,
    RESEARCH_EXPENSE as research_expense,
    RESEARCH_EXPENSE_YOY as research_expense_yoy,
    SURRENDER_VALUE as surrender_value,
    SURRENDER_VALUE_YOY as surrender_value_yoy,
    NET_COMPENSATE_EXPENSE as net_compensate_expense,
    NET_COMPENSATE_EXPENSE_YOY as net_compensate_expense_yoy,
    NET_CONTRACT_RESERVE as net_contract_reserve,
    NET_CONTRACT_RESERVE_YOY as net_contract_reserve_yoy,
    POLICY_BONUS_EXPENSE as policy_bonus_expense,
    POLICY_BONUS_EXPENSE_YOY as policy_bonus_expense_yoy,
    REINSURE_EXPENSE as reinsure_expense,
    REINSURE_EXPENSE_YOY as reinsure_expense_yoy,
    OTHER_BUSINESS_COST as other_business_cost,
    OTHER_BUSINESS_COST_YOY as other_business_cost_yoy,
    OPERATE_TAX_ADD as operate_tax_add,
    OPERATE_TAX_ADD_YOY as operate_tax_add_yoy,
    SALE_EXPENSE as sale_expense,
    SALE_EXPENSE_YOY as sale_expense_yoy,
    MANAGE_EXPENSE as manage_expense,
    MANAGE_EXPENSE_YOY as manage_expense_yoy,
    ME_RESEARCH_EXPENSE as me_research_expense,
    ME_RESEARCH_EXPENSE_YOY as me_research_expense_yoy,
    FINANCE_EXPENSE as finance_expense,
    FINANCE_EXPENSE_YOY as finance_expense_yoy,
    FE_INTEREST_EXPENSE as fe_interest_expense,
    FE_INTEREST_EXPENSE_YOY as fe_interest_expense_yoy,
    FE_INTEREST_INCOME as fe_interest_income,
    FE_INTEREST_INCOME_YOY as fe_interest_income_yoy,
    ASSET_IMPAIRMENT_LOSS as asset_impairment_loss,
    ASSET_IMPAIRMENT_LOSS_YOY as asset_impairment_loss_yoy,
    CREDIT_IMPAIRMENT_LOSS as credit_impairment_loss,
    CREDIT_IMPAIRMENT_LOSS_YOY as credit_impairment_loss_yoy,
    TOC_OTHER as toc_other,
    TOC_OTHER_YOY as toc_other_yoy,
    FAIRVALUE_CHANGE_INCOME as fairvalue_change_income,
    FAIRVALUE_CHANGE_INCOME_YOY as fairvalue_change_income_yoy,
    INVEST_INCOME as invest_income,
    INVEST_INCOME_YOY as invest_income_yoy,
    INVEST_JOINT_INCOME as invest_joint_income,
    INVEST_JOINT_INCOME_YOY as invest_joint_income_yoy,
    NET_EXPOSURE_INCOME as net_exposure_income,
    NET_EXPOSURE_INCOME_YOY as net_exposure_income_yoy,
    EXCHANGE_INCOME as exchange_income,
    EXCHANGE_INCOME_YOY as exchange_income_yoy,
    ASSET_DISPOSAL_INCOME as asset_disposal_income,
    ASSET_DISPOSAL_INCOME_YOY as asset_disposal_income_yoy,
    ASSET_IMPAIRMENT_INCOME as asset_impairment_income,
    ASSET_IMPAIRMENT_INCOME_YOY as asset_impairment_income_yoy,
    CREDIT_IMPAIRMENT_INCOME as credit_impairment_income,
    CREDIT_IMPAIRMENT_INCOME_YOY as credit_impairment_income_yoy,
    OTHER_INCOME as other_income,
    OTHER_INCOME_YOY as other_income_yoy,
    OPERATE_PROFIT_OTHER as operate_profit_other,
    OPERATE_PROFIT_OTHER_YOY as operate_profit_other_yoy,
    OPERATE_PROFIT_BALANCE as operate_profit_balance,
    OPERATE_PROFIT_BALANCE_YOY as operate_profit_balance_yoy,
    OPERATE_PROFIT as operate_profit,
    OPERATE_PROFIT_YOY as operate_profit_yoy,
    NONBUSINESS_INCOME as nonbusiness_income,
    NONBUSINESS_INCOME_YOY as nonbusiness_income_yoy,
    NONCURRENT_DISPOSAL_INCOME as noncurrent_disposal_income,
    NONCURRENT_DISPOSAL_INCOME_YOY as noncurrent_disposal_income_yoy,
    NONBUSINESS_EXPENSE as nonbusiness_expense,
    NONBUSINESS_EXPENSE_YOY as nonbusiness_expense_yoy,
    NONCURRENT_DISPOSAL_LOSS as noncurrent_disposal_loss,
    NONCURRENT_DISPOSAL_LOSS_YOY as noncurrent_disposal_loss_yoy,
    EFFECT_TP_OTHER as effect_tp_other,
    EFFECT_TP_OTHER_YOY as effect_tp_other_yoy,
    TOTAL_PROFIT_BALANCE as total_profit_balance,
    TOTAL_PROFIT_BALANCE_YOY as total_profit_balance_yoy,
    TOTAL_PROFIT as total_profit,
    TOTAL_PROFIT_YOY as total_profit_yoy,
    INCOME_TAX as income_tax,
    INCOME_TAX_YOY as income_tax_yoy,
    EFFECT_NETPROFIT_OTHER as effect_netprofit_other,
    EFFECT_NETPROFIT_OTHER_YOY as effect_netprofit_other_yoy,
    EFFECT_NETPROFIT_BALANCE as effect_netprofit_balance,
    EFFECT_NETPROFIT_BALANCE_YOY as effect_netprofit_balance_yoy,
    UNCONFIRM_INVEST_LOSS as unconfirm_invest_loss,
    UNCONFIRM_INVEST_LOSS_YOY as unconfirm_invest_loss_yoy,
    NETPROFIT as netprofit,
    NETPROFIT_YOY as netprofit_yoy,
    PRECOMBINE_PROFIT as precombine_profit,
    PRECOMBINE_PROFIT_YOY as precombine_profit_yoy,
    CONTINUED_NETPROFIT as continued_netprofit,
    CONTINUED_NETPROFIT_YOY as continued_netprofit_yoy,
    DISCONTINUED_NETPROFIT as discontinued_netprofit,
    DISCONTINUED_NETPROFIT_YOY as discontinued_netprofit_yoy,
    PARENT_NETPROFIT as parent_netprofit,
    PARENT_NETPROFIT_YOY as parent_netprofit_yoy,
    MINORITY_INTEREST as minority_interest,
    MINORITY_INTEREST_YOY as minority_interest_yoy,
    DEDUCT_PARENT_NETPROFIT as deduct_parent_netprofit,
    DEDUCT_PARENT_NETPROFIT_YOY as deduct_parent_netprofit_yoy,
    NETPROFIT_OTHER as netprofit_other,
    NETPROFIT_OTHER_YOY as netprofit_other_yoy,
    NETPROFIT_BALANCE as netprofit_balance,
    NETPROFIT_BALANCE_YOY as netprofit_balance_yoy,
    BASIC_EPS as basic_eps,
    BASIC_EPS_YOY as basic_eps_yoy,
    DILUTED_EPS as diluted_eps,
    DILUTED_EPS_YOY as diluted_eps_yoy,
    OTHER_COMPRE_INCOME as other_compre_income,
    OTHER_COMPRE_INCOME_YOY as other_compre_income_yoy,
    PARENT_OCI as parent_oci,
    PARENT_OCI_YOY as parent_oci_yoy,
    MINORITY_OCI as minority_oci,
    MINORITY_OCI_YOY as minority_oci_yoy,
    PARENT_OCI_OTHER as parent_oci_other,
    PARENT_OCI_OTHER_YOY as parent_oci_other_yoy,
    PARENT_OCI_BALANCE as parent_oci_balance,
    PARENT_OCI_BALANCE_YOY as parent_oci_balance_yoy,
    UNABLE_OCI as unable_oci,
    UNABLE_OCI_YOY as unable_oci_yoy,
    CREDITRISK_FAIRVALUE_CHANGE as creditrisk_fairvalue_change,
    CREDITRISK_FAIRVALUE_CHANGE_YOY as creditrisk_fairvalue_change_yoy,
    OTHERRIGHT_FAIRVALUE_CHANGE as otherright_fairvalue_change,
    OTHERRIGHT_FAIRVALUE_CHANGE_YOY as otherright_fairvalue_change_yoy,
    SETUP_PROFIT_CHANGE as setup_profit_change,
    SETUP_PROFIT_CHANGE_YOY as setup_profit_change_yoy,
    RIGHTLAW_UNABLE_OCI as rightlaw_unable_oci,
    RIGHTLAW_UNABLE_OCI_YOY as rightlaw_unable_oci_yoy,
    UNABLE_OCI_OTHER as unable_oci_other,
    UNABLE_OCI_OTHER_YOY as unable_oci_other_yoy,
    UNABLE_OCI_BALANCE as unable_oci_balance,
    UNABLE_OCI_BALANCE_YOY as unable_oci_balance_yoy,
    ABLE_OCI as able_oci,
    ABLE_OCI_YOY as able_oci_yoy,
    RIGHTLAW_ABLE_OCI as rightlaw_able_oci,
    RIGHTLAW_ABLE_OCI_YOY as rightlaw_able_oci_yoy,
    AFA_FAIRVALUE_CHANGE as afa_fairvalue_change,
    AFA_FAIRVALUE_CHANGE_YOY as afa_fairvalue_change_yoy,
    HMI_AFA as hmi_afa,
    HMI_AFA_YOY as hmi_afa_yoy,
    CASHFLOW_HEDGE_VALID as cashflow_hedge_valid,
    CASHFLOW_HEDGE_VALID_YOY as cashflow_hedge_valid_yoy,
    CREDITOR_FAIRVALUE_CHANGE as creditor_fairvalue_change,
    CREDITOR_FAIRVALUE_CHANGE_YOY as creditor_fairvalue_change_yoy,
    CREDITOR_IMPAIRMENT_RESERVE as creditor_impairment_reserve,
    CREDITOR_IMPAIRMENT_RESERVE_YOY as creditor_impairment_reserve_yoy,
    FINANCE_OCI_AMT as finance_oci_amt,
    FINANCE_OCI_AMT_YOY as finance_oci_amt_yoy,
    CONVERT_DIFF as convert_diff,
    CONVERT_DIFF_YOY as convert_diff_yoy,
    ABLE_OCI_OTHER as able_oci_other,
    ABLE_OCI_OTHER_YOY as able_oci_other_yoy,
    ABLE_OCI_BALANCE as able_oci_balance,
    ABLE_OCI_BALANCE_YOY as able_oci_balance_yoy,
    OCI_OTHER as oci_other,
    OCI_OTHER_YOY as oci_other_yoy,
    OCI_BALANCE as oci_balance,
    OCI_BALANCE_YOY as oci_balance_yoy,
    TOTAL_COMPRE_INCOME as total_compre_income,
    TOTAL_COMPRE_INCOME_YOY as total_compre_income_yoy,
    PARENT_TCI as parent_tci,
    PARENT_TCI_YOY as parent_tci_yoy,
    MINORITY_TCI as minority_tci,
    MINORITY_TCI_YOY as minority_tci_yoy,
    PRECOMBINE_TCI as precombine_tci,
    PRECOMBINE_TCI_YOY as precombine_tci_yoy,
    EFFECT_TCI_BALANCE as effect_tci_balance,
    EFFECT_TCI_BALANCE_YOY as effect_tci_balance_yoy,
    TCI_OTHER as tci_other,
    TCI_OTHER_YOY as tci_other_yoy,
    TCI_BALANCE as tci_balance,
    TCI_BALANCE_YOY as tci_balance_yoy,
    ACF_END_INCOME as acf_end_income,
    ACF_END_INCOME_YOY as acf_end_income_yoy,
    OPINION_TYPE as opinion_type
from source
