with source as (
    select
        SECUCODE,
        SECURITY_CODE,
        SECURITY_NAME_ABBR,
        ORG_CODE,
        ORG_TYPE,
        REPORT_DATE,
        REPORT_TYPE,
        REPORT_DATE_NAME,
        SECURITY_TYPE_CODE,
        NOTICE_DATE,
        UPDATE_DATE,
        CURRENCY,
        ACCEPT_DEPOSIT_INTERBANK,
        ACCOUNTS_PAYABLE,
        ACCOUNTS_RECE,
        ACCRUED_EXPENSE,
        ADVANCE_RECEIVABLES,
        AGENT_TRADE_SECURITY,
        AGENT_UNDERWRITE_SECURITY,
        AMORTIZE_COST_FINASSET,
        AMORTIZE_COST_FINLIAB,
        AMORTIZE_COST_NCFINASSET,
        AMORTIZE_COST_NCFINLIAB,
        APPOINT_FVTPL_FINASSET,
        APPOINT_FVTPL_FINLIAB,
        ASSET_BALANCE,
        ASSET_OTHER,
        ASSIGN_CASH_DIVIDEND,
        AVAILABLE_SALE_FINASSET,
        BOND_PAYABLE,
        BORROW_FUND,
        BUY_RESALE_FINASSET,
        CAPITAL_RESERVE,
        CIP,
        CONSUMPTIVE_BIOLOGICAL_ASSET,
        CONTRACT_ASSET,
        CONTRACT_LIAB,
        CONVERT_DIFF,
        CREDITOR_INVEST,
        CURRENT_ASSET_BALANCE,
        CURRENT_ASSET_OTHER,
        CURRENT_LIAB_BALANCE,
        CURRENT_LIAB_OTHER,
        DEFER_INCOME,
        DEFER_INCOME_1YEAR,
        DEFER_TAX_ASSET,
        DEFER_TAX_LIAB,
        DERIVE_FINASSET,
        DERIVE_FINLIAB,
        DEVELOP_EXPENSE,
        DIV_HOLDSALE_ASSET,
        DIV_HOLDSALE_LIAB,
        DIVIDEND_PAYABLE,
        DIVIDEND_RECE,
        EQUITY_BALANCE,
        EQUITY_OTHER,
        EXPORT_REFUND_RECE,
        FEE_COMMISSION_PAYABLE,
        FIN_FUND,
        FINANCE_RECE,
        FIXED_ASSET,
        FIXED_ASSET_DISPOSAL,
        FVTOCI_FINASSET,
        FVTOCI_NCFINASSET,
        FVTPL_FINASSET,
        FVTPL_FINLIAB,
        GENERAL_RISK_RESERVE,
        GOODWILL,
        HOLD_MATURITY_INVEST,
        HOLDSALE_ASSET,
        HOLDSALE_LIAB,
        INSURANCE_CONTRACT_RESERVE,
        INTANGIBLE_ASSET,
        INTEREST_PAYABLE,
        INTEREST_RECE,
        INTERNAL_PAYABLE,
        INTERNAL_RECE,
        INVENTORY,
        INVEST_REALESTATE,
        LEASE_LIAB,
        LEND_FUND,
        LIAB_BALANCE,
        LIAB_EQUITY_BALANCE,
        LIAB_EQUITY_OTHER,
        LIAB_OTHER,
        LOAN_ADVANCE,
        LOAN_PBC,
        LONG_EQUITY_INVEST,
        LONG_LOAN,
        LONG_PAYABLE,
        LONG_PREPAID_EXPENSE,
        LONG_RECE,
        LONG_STAFFSALARY_PAYABLE,
        MINORITY_EQUITY,
        MONETARYFUNDS,
        NONCURRENT_ASSET_1YEAR,
        NONCURRENT_ASSET_BALANCE,
        NONCURRENT_ASSET_OTHER,
        NONCURRENT_LIAB_1YEAR,
        NONCURRENT_LIAB_BALANCE,
        NONCURRENT_LIAB_OTHER,
        NOTE_ACCOUNTS_PAYABLE,
        NOTE_ACCOUNTS_RECE,
        NOTE_PAYABLE,
        NOTE_RECE,
        OIL_GAS_ASSET,
        OTHER_COMPRE_INCOME,
        OTHER_CREDITOR_INVEST,
        OTHER_CURRENT_ASSET,
        OTHER_CURRENT_LIAB,
        OTHER_EQUITY_INVEST,
        OTHER_EQUITY_OTHER,
        OTHER_EQUITY_TOOL,
        OTHER_NONCURRENT_ASSET,
        OTHER_NONCURRENT_FINASSET,
        OTHER_NONCURRENT_LIAB,
        OTHER_PAYABLE,
        OTHER_RECE,
        PARENT_EQUITY_BALANCE,
        PARENT_EQUITY_OTHER,
        PERPETUAL_BOND,
        PERPETUAL_BOND_PAYBALE,
        PREDICT_CURRENT_LIAB,
        PREDICT_LIAB,
        PREFERRED_SHARES,
        PREFERRED_SHARES_PAYBALE,
        PREMIUM_RECE,
        PREPAYMENT,
        PRODUCTIVE_BIOLOGY_ASSET,
        PROJECT_MATERIAL,
        RC_RESERVE_RECE,
        REINSURE_PAYABLE,
        REINSURE_RECE,
        SELL_REPO_FINASSET,
        SETTLE_EXCESS_RESERVE,
        SHARE_CAPITAL,
        SHORT_BOND_PAYABLE,
        SHORT_FIN_PAYABLE,
        SHORT_LOAN,
        SPECIAL_PAYABLE,
        SPECIAL_RESERVE,
        STAFF_SALARY_PAYABLE,
        SUBSIDY_RECE,
        SURPLUS_RESERVE,
        TAX_PAYABLE,
        TOTAL_ASSETS,
        TOTAL_CURRENT_ASSETS,
        TOTAL_CURRENT_LIAB,
        TOTAL_EQUITY,
        TOTAL_LIAB_EQUITY,
        TOTAL_LIABILITIES,
        TOTAL_NONCURRENT_ASSETS,
        TOTAL_NONCURRENT_LIAB,
        TOTAL_OTHER_PAYABLE,
        TOTAL_OTHER_RECE,
        TOTAL_PARENT_EQUITY,
        TRADE_FINASSET,
        TRADE_FINASSET_NOTFVTPL,
        TRADE_FINLIAB,
        TRADE_FINLIAB_NOTFVTPL,
        TREASURY_SHARES,
        UNASSIGN_RPOFIT,
        UNCONFIRM_INVEST_LOSS,
        USERIGHT_ASSET,
        ACCEPT_DEPOSIT_INTERBANK_YOY,
        ACCOUNTS_PAYABLE_YOY,
        ACCOUNTS_RECE_YOY,
        ACCRUED_EXPENSE_YOY,
        ADVANCE_RECEIVABLES_YOY,
        AGENT_TRADE_SECURITY_YOY,
        AGENT_UNDERWRITE_SECURITY_YOY,
        AMORTIZE_COST_FINASSET_YOY,
        AMORTIZE_COST_FINLIAB_YOY,
        AMORTIZE_COST_NCFINASSET_YOY,
        AMORTIZE_COST_NCFINLIAB_YOY,
        APPOINT_FVTPL_FINASSET_YOY,
        APPOINT_FVTPL_FINLIAB_YOY,
        ASSET_BALANCE_YOY,
        ASSET_OTHER_YOY,
        ASSIGN_CASH_DIVIDEND_YOY,
        AVAILABLE_SALE_FINASSET_YOY,
        BOND_PAYABLE_YOY,
        BORROW_FUND_YOY,
        BUY_RESALE_FINASSET_YOY,
        CAPITAL_RESERVE_YOY,
        CIP_YOY,
        CONSUMPTIVE_BIOLOGICAL_ASSET_YOY,
        CONTRACT_ASSET_YOY,
        CONTRACT_LIAB_YOY,
        CONVERT_DIFF_YOY,
        CREDITOR_INVEST_YOY,
        CURRENT_ASSET_BALANCE_YOY,
        CURRENT_ASSET_OTHER_YOY,
        CURRENT_LIAB_BALANCE_YOY,
        CURRENT_LIAB_OTHER_YOY,
        DEFER_INCOME_1YEAR_YOY,
        DEFER_INCOME_YOY,
        DEFER_TAX_ASSET_YOY,
        DEFER_TAX_LIAB_YOY,
        DERIVE_FINASSET_YOY,
        DERIVE_FINLIAB_YOY,
        DEVELOP_EXPENSE_YOY,
        DIV_HOLDSALE_ASSET_YOY,
        DIV_HOLDSALE_LIAB_YOY,
        DIVIDEND_PAYABLE_YOY,
        DIVIDEND_RECE_YOY,
        EQUITY_BALANCE_YOY,
        EQUITY_OTHER_YOY,
        EXPORT_REFUND_RECE_YOY,
        FEE_COMMISSION_PAYABLE_YOY,
        FIN_FUND_YOY,
        FINANCE_RECE_YOY,
        FIXED_ASSET_DISPOSAL_YOY,
        FIXED_ASSET_YOY,
        FVTOCI_FINASSET_YOY,
        FVTOCI_NCFINASSET_YOY,
        FVTPL_FINASSET_YOY,
        FVTPL_FINLIAB_YOY,
        GENERAL_RISK_RESERVE_YOY,
        GOODWILL_YOY,
        HOLD_MATURITY_INVEST_YOY,
        HOLDSALE_ASSET_YOY,
        HOLDSALE_LIAB_YOY,
        INSURANCE_CONTRACT_RESERVE_YOY,
        INTANGIBLE_ASSET_YOY,
        INTEREST_PAYABLE_YOY,
        INTEREST_RECE_YOY,
        INTERNAL_PAYABLE_YOY,
        INTERNAL_RECE_YOY,
        INVENTORY_YOY,
        INVEST_REALESTATE_YOY,
        LEASE_LIAB_YOY,
        LEND_FUND_YOY,
        LIAB_BALANCE_YOY,
        LIAB_EQUITY_BALANCE_YOY,
        LIAB_EQUITY_OTHER_YOY,
        LIAB_OTHER_YOY,
        LOAN_ADVANCE_YOY,
        LOAN_PBC_YOY,
        LONG_EQUITY_INVEST_YOY,
        LONG_LOAN_YOY,
        LONG_PAYABLE_YOY,
        LONG_PREPAID_EXPENSE_YOY,
        LONG_RECE_YOY,
        LONG_STAFFSALARY_PAYABLE_YOY,
        MINORITY_EQUITY_YOY,
        MONETARYFUNDS_YOY,
        NONCURRENT_ASSET_1YEAR_YOY,
        NONCURRENT_ASSET_BALANCE_YOY,
        NONCURRENT_ASSET_OTHER_YOY,
        NONCURRENT_LIAB_1YEAR_YOY,
        NONCURRENT_LIAB_BALANCE_YOY,
        NONCURRENT_LIAB_OTHER_YOY,
        NOTE_ACCOUNTS_PAYABLE_YOY,
        NOTE_ACCOUNTS_RECE_YOY,
        NOTE_PAYABLE_YOY,
        NOTE_RECE_YOY,
        OIL_GAS_ASSET_YOY,
        OTHER_COMPRE_INCOME_YOY,
        OTHER_CREDITOR_INVEST_YOY,
        OTHER_CURRENT_ASSET_YOY,
        OTHER_CURRENT_LIAB_YOY,
        OTHER_EQUITY_INVEST_YOY,
        OTHER_EQUITY_OTHER_YOY,
        OTHER_EQUITY_TOOL_YOY,
        OTHER_NONCURRENT_ASSET_YOY,
        OTHER_NONCURRENT_FINASSET_YOY,
        OTHER_NONCURRENT_LIAB_YOY,
        OTHER_PAYABLE_YOY,
        OTHER_RECE_YOY,
        PARENT_EQUITY_BALANCE_YOY,
        PARENT_EQUITY_OTHER_YOY,
        PERPETUAL_BOND_PAYBALE_YOY,
        PERPETUAL_BOND_YOY,
        PREDICT_CURRENT_LIAB_YOY,
        PREDICT_LIAB_YOY,
        PREFERRED_SHARES_PAYBALE_YOY,
        PREFERRED_SHARES_YOY,
        PREMIUM_RECE_YOY,
        PREPAYMENT_YOY,
        PRODUCTIVE_BIOLOGY_ASSET_YOY,
        PROJECT_MATERIAL_YOY,
        RC_RESERVE_RECE_YOY,
        REINSURE_PAYABLE_YOY,
        REINSURE_RECE_YOY,
        SELL_REPO_FINASSET_YOY,
        SETTLE_EXCESS_RESERVE_YOY,
        SHARE_CAPITAL_YOY,
        SHORT_BOND_PAYABLE_YOY,
        SHORT_FIN_PAYABLE_YOY,
        SHORT_LOAN_YOY,
        SPECIAL_PAYABLE_YOY,
        SPECIAL_RESERVE_YOY,
        STAFF_SALARY_PAYABLE_YOY,
        SUBSIDY_RECE_YOY,
        SURPLUS_RESERVE_YOY,
        TAX_PAYABLE_YOY,
        TOTAL_ASSETS_YOY,
        TOTAL_CURRENT_ASSETS_YOY,
        TOTAL_CURRENT_LIAB_YOY,
        TOTAL_EQUITY_YOY,
        TOTAL_LIAB_EQUITY_YOY,
        TOTAL_LIABILITIES_YOY,
        TOTAL_NONCURRENT_ASSETS_YOY,
        TOTAL_NONCURRENT_LIAB_YOY,
        TOTAL_OTHER_PAYABLE_YOY,
        TOTAL_OTHER_RECE_YOY,
        TOTAL_PARENT_EQUITY_YOY,
        TRADE_FINASSET_NOTFVTPL_YOY,
        TRADE_FINASSET_YOY,
        TRADE_FINLIAB_NOTFVTPL_YOY,
        TRADE_FINLIAB_YOY,
        TREASURY_SHARES_YOY,
        UNASSIGN_RPOFIT_YOY,
        UNCONFIRM_INVEST_LOSS_YOY,
        USERIGHT_ASSET_YOY,
        OPINION_TYPE,
        OSOPINION_TYPE,
        LISTING_STATE
    from {{ source('raw', 'eastmoney__balance') }}
)

select
    {{ normalize_cn_security_code('SECUCODE', input_format='eastmoney_suffix') }} as security_code,
    toString(SECURITY_CODE) as security_local_code,
    SECURITY_NAME_ABBR as security_name_abbr,
    ORG_CODE as org_code,
    ORG_TYPE as org_type,
    REPORT_DATE as report_date,
    REPORT_TYPE as report_type,
    REPORT_DATE_NAME as report_date_name,
    SECURITY_TYPE_CODE as security_type_code,
    NOTICE_DATE as notice_date,
    UPDATE_DATE as update_date,
    CURRENCY as currency,
    ACCEPT_DEPOSIT_INTERBANK as accept_deposit_interbank,
    ACCOUNTS_PAYABLE as accounts_payable,
    ACCOUNTS_RECE as accounts_rece,
    ACCRUED_EXPENSE as accrued_expense,
    ADVANCE_RECEIVABLES as advance_receivables,
    AGENT_TRADE_SECURITY as agent_trade_security,
    AGENT_UNDERWRITE_SECURITY as agent_underwrite_security,
    AMORTIZE_COST_FINASSET as amortize_cost_finasset,
    AMORTIZE_COST_FINLIAB as amortize_cost_finliab,
    AMORTIZE_COST_NCFINASSET as amortize_cost_ncfinasset,
    AMORTIZE_COST_NCFINLIAB as amortize_cost_ncfinliab,
    APPOINT_FVTPL_FINASSET as appoint_fvtpl_finasset,
    APPOINT_FVTPL_FINLIAB as appoint_fvtpl_finliab,
    ASSET_BALANCE as asset_balance,
    ASSET_OTHER as asset_other,
    ASSIGN_CASH_DIVIDEND as assign_cash_dividend,
    AVAILABLE_SALE_FINASSET as available_sale_finasset,
    BOND_PAYABLE as bond_payable,
    BORROW_FUND as borrow_fund,
    BUY_RESALE_FINASSET as buy_resale_finasset,
    CAPITAL_RESERVE as capital_reserve,
    CIP as cip,
    CONSUMPTIVE_BIOLOGICAL_ASSET as consumptive_biological_asset,
    CONTRACT_ASSET as contract_asset,
    CONTRACT_LIAB as contract_liab,
    CONVERT_DIFF as convert_diff,
    CREDITOR_INVEST as creditor_invest,
    CURRENT_ASSET_BALANCE as current_asset_balance,
    CURRENT_ASSET_OTHER as current_asset_other,
    CURRENT_LIAB_BALANCE as current_liab_balance,
    CURRENT_LIAB_OTHER as current_liab_other,
    DEFER_INCOME as defer_income,
    DEFER_INCOME_1YEAR as defer_income_1year,
    DEFER_TAX_ASSET as defer_tax_asset,
    DEFER_TAX_LIAB as defer_tax_liab,
    DERIVE_FINASSET as derive_finasset,
    DERIVE_FINLIAB as derive_finliab,
    DEVELOP_EXPENSE as develop_expense,
    DIV_HOLDSALE_ASSET as div_holdsale_asset,
    DIV_HOLDSALE_LIAB as div_holdsale_liab,
    DIVIDEND_PAYABLE as dividend_payable,
    DIVIDEND_RECE as dividend_rece,
    EQUITY_BALANCE as equity_balance,
    EQUITY_OTHER as equity_other,
    EXPORT_REFUND_RECE as export_refund_rece,
    FEE_COMMISSION_PAYABLE as fee_commission_payable,
    FIN_FUND as fin_fund,
    FINANCE_RECE as finance_rece,
    FIXED_ASSET as fixed_asset,
    FIXED_ASSET_DISPOSAL as fixed_asset_disposal,
    FVTOCI_FINASSET as fvtoci_finasset,
    FVTOCI_NCFINASSET as fvtoci_ncfinasset,
    FVTPL_FINASSET as fvtpl_finasset,
    FVTPL_FINLIAB as fvtpl_finliab,
    GENERAL_RISK_RESERVE as general_risk_reserve,
    GOODWILL as goodwill,
    HOLD_MATURITY_INVEST as hold_maturity_invest,
    HOLDSALE_ASSET as holdsale_asset,
    HOLDSALE_LIAB as holdsale_liab,
    INSURANCE_CONTRACT_RESERVE as insurance_contract_reserve,
    INTANGIBLE_ASSET as intangible_asset,
    INTEREST_PAYABLE as interest_payable,
    INTEREST_RECE as interest_rece,
    INTERNAL_PAYABLE as internal_payable,
    INTERNAL_RECE as internal_rece,
    INVENTORY as inventory,
    INVEST_REALESTATE as invest_realestate,
    LEASE_LIAB as lease_liab,
    LEND_FUND as lend_fund,
    LIAB_BALANCE as liab_balance,
    LIAB_EQUITY_BALANCE as liab_equity_balance,
    LIAB_EQUITY_OTHER as liab_equity_other,
    LIAB_OTHER as liab_other,
    LOAN_ADVANCE as loan_advance,
    LOAN_PBC as loan_pbc,
    LONG_EQUITY_INVEST as long_equity_invest,
    LONG_LOAN as long_loan,
    LONG_PAYABLE as long_payable,
    LONG_PREPAID_EXPENSE as long_prepaid_expense,
    LONG_RECE as long_rece,
    LONG_STAFFSALARY_PAYABLE as long_staffsalary_payable,
    MINORITY_EQUITY as minority_equity,
    MONETARYFUNDS as monetary_funds,
    NONCURRENT_ASSET_1YEAR as noncurrent_asset_1year,
    NONCURRENT_ASSET_BALANCE as noncurrent_asset_balance,
    NONCURRENT_ASSET_OTHER as noncurrent_asset_other,
    NONCURRENT_LIAB_1YEAR as noncurrent_liab_1year,
    NONCURRENT_LIAB_BALANCE as noncurrent_liab_balance,
    NONCURRENT_LIAB_OTHER as noncurrent_liab_other,
    NOTE_ACCOUNTS_PAYABLE as note_accounts_payable,
    NOTE_ACCOUNTS_RECE as note_accounts_rece,
    NOTE_PAYABLE as note_payable,
    NOTE_RECE as note_rece,
    OIL_GAS_ASSET as oil_gas_asset,
    OTHER_COMPRE_INCOME as other_compre_income,
    OTHER_CREDITOR_INVEST as other_creditor_invest,
    OTHER_CURRENT_ASSET as other_current_asset,
    OTHER_CURRENT_LIAB as other_current_liab,
    OTHER_EQUITY_INVEST as other_equity_invest,
    OTHER_EQUITY_OTHER as other_equity_other,
    OTHER_EQUITY_TOOL as other_equity_tool,
    OTHER_NONCURRENT_ASSET as other_noncurrent_asset,
    OTHER_NONCURRENT_FINASSET as other_noncurrent_finasset,
    OTHER_NONCURRENT_LIAB as other_noncurrent_liab,
    OTHER_PAYABLE as other_payable,
    OTHER_RECE as other_rece,
    PARENT_EQUITY_BALANCE as parent_equity_balance,
    PARENT_EQUITY_OTHER as parent_equity_other,
    PERPETUAL_BOND as perpetual_bond,
    PERPETUAL_BOND_PAYBALE as perpetual_bond_payable,
    PREDICT_CURRENT_LIAB as predict_current_liab,
    PREDICT_LIAB as predict_liab,
    PREFERRED_SHARES as preferred_shares,
    PREFERRED_SHARES_PAYBALE as preferred_shares_payable,
    PREMIUM_RECE as premium_rece,
    PREPAYMENT as prepayment,
    PRODUCTIVE_BIOLOGY_ASSET as productive_biology_asset,
    PROJECT_MATERIAL as project_material,
    RC_RESERVE_RECE as rc_reserve_rece,
    REINSURE_PAYABLE as reinsure_payable,
    REINSURE_RECE as reinsure_rece,
    SELL_REPO_FINASSET as sell_repo_finasset,
    SETTLE_EXCESS_RESERVE as settle_excess_reserve,
    SHARE_CAPITAL as share_capital,
    SHORT_BOND_PAYABLE as short_bond_payable,
    SHORT_FIN_PAYABLE as short_fin_payable,
    SHORT_LOAN as short_loan,
    SPECIAL_PAYABLE as special_payable,
    SPECIAL_RESERVE as special_reserve,
    STAFF_SALARY_PAYABLE as staff_salary_payable,
    SUBSIDY_RECE as subsidy_rece,
    SURPLUS_RESERVE as surplus_reserve,
    TAX_PAYABLE as tax_payable,
    TOTAL_ASSETS as total_assets,
    TOTAL_CURRENT_ASSETS as total_current_assets,
    TOTAL_CURRENT_LIAB as total_current_liab,
    TOTAL_EQUITY as total_equity,
    TOTAL_LIAB_EQUITY as total_liab_equity,
    TOTAL_LIABILITIES as total_liabilities,
    TOTAL_NONCURRENT_ASSETS as total_noncurrent_assets,
    TOTAL_NONCURRENT_LIAB as total_noncurrent_liab,
    TOTAL_OTHER_PAYABLE as total_other_payable,
    TOTAL_OTHER_RECE as total_other_rece,
    TOTAL_PARENT_EQUITY as total_parent_equity,
    TRADE_FINASSET as trade_finasset,
    TRADE_FINASSET_NOTFVTPL as trade_finasset_notfvtpl,
    TRADE_FINLIAB as trade_finliab,
    TRADE_FINLIAB_NOTFVTPL as trade_finliab_notfvtpl,
    TREASURY_SHARES as treasury_shares,
    UNASSIGN_RPOFIT as unassigned_profit,
    UNCONFIRM_INVEST_LOSS as unconfirm_invest_loss,
    USERIGHT_ASSET as use_right_asset,
    ACCEPT_DEPOSIT_INTERBANK_YOY as accept_deposit_interbank_yoy,
    ACCOUNTS_PAYABLE_YOY as accounts_payable_yoy,
    ACCOUNTS_RECE_YOY as accounts_rece_yoy,
    ACCRUED_EXPENSE_YOY as accrued_expense_yoy,
    ADVANCE_RECEIVABLES_YOY as advance_receivables_yoy,
    AGENT_TRADE_SECURITY_YOY as agent_trade_security_yoy,
    AGENT_UNDERWRITE_SECURITY_YOY as agent_underwrite_security_yoy,
    AMORTIZE_COST_FINASSET_YOY as amortize_cost_finasset_yoy,
    AMORTIZE_COST_FINLIAB_YOY as amortize_cost_finliab_yoy,
    AMORTIZE_COST_NCFINASSET_YOY as amortize_cost_ncfinasset_yoy,
    AMORTIZE_COST_NCFINLIAB_YOY as amortize_cost_ncfinliab_yoy,
    APPOINT_FVTPL_FINASSET_YOY as appoint_fvtpl_finasset_yoy,
    APPOINT_FVTPL_FINLIAB_YOY as appoint_fvtpl_finliab_yoy,
    ASSET_BALANCE_YOY as asset_balance_yoy,
    ASSET_OTHER_YOY as asset_other_yoy,
    ASSIGN_CASH_DIVIDEND_YOY as assign_cash_dividend_yoy,
    AVAILABLE_SALE_FINASSET_YOY as available_sale_finasset_yoy,
    BOND_PAYABLE_YOY as bond_payable_yoy,
    BORROW_FUND_YOY as borrow_fund_yoy,
    BUY_RESALE_FINASSET_YOY as buy_resale_finasset_yoy,
    CAPITAL_RESERVE_YOY as capital_reserve_yoy,
    CIP_YOY as cip_yoy,
    CONSUMPTIVE_BIOLOGICAL_ASSET_YOY as consumptive_biological_asset_yoy,
    CONTRACT_ASSET_YOY as contract_asset_yoy,
    CONTRACT_LIAB_YOY as contract_liab_yoy,
    CONVERT_DIFF_YOY as convert_diff_yoy,
    CREDITOR_INVEST_YOY as creditor_invest_yoy,
    CURRENT_ASSET_BALANCE_YOY as current_asset_balance_yoy,
    CURRENT_ASSET_OTHER_YOY as current_asset_other_yoy,
    CURRENT_LIAB_BALANCE_YOY as current_liab_balance_yoy,
    CURRENT_LIAB_OTHER_YOY as current_liab_other_yoy,
    DEFER_INCOME_1YEAR_YOY as defer_income_1year_yoy,
    DEFER_INCOME_YOY as defer_income_yoy,
    DEFER_TAX_ASSET_YOY as defer_tax_asset_yoy,
    DEFER_TAX_LIAB_YOY as defer_tax_liab_yoy,
    DERIVE_FINASSET_YOY as derive_finasset_yoy,
    DERIVE_FINLIAB_YOY as derive_finliab_yoy,
    DEVELOP_EXPENSE_YOY as develop_expense_yoy,
    DIV_HOLDSALE_ASSET_YOY as div_holdsale_asset_yoy,
    DIV_HOLDSALE_LIAB_YOY as div_holdsale_liab_yoy,
    DIVIDEND_PAYABLE_YOY as dividend_payable_yoy,
    DIVIDEND_RECE_YOY as dividend_rece_yoy,
    EQUITY_BALANCE_YOY as equity_balance_yoy,
    EQUITY_OTHER_YOY as equity_other_yoy,
    EXPORT_REFUND_RECE_YOY as export_refund_rece_yoy,
    FEE_COMMISSION_PAYABLE_YOY as fee_commission_payable_yoy,
    FIN_FUND_YOY as fin_fund_yoy,
    FINANCE_RECE_YOY as finance_rece_yoy,
    FIXED_ASSET_DISPOSAL_YOY as fixed_asset_disposal_yoy,
    FIXED_ASSET_YOY as fixed_asset_yoy,
    FVTOCI_FINASSET_YOY as fvtoci_finasset_yoy,
    FVTOCI_NCFINASSET_YOY as fvtoci_ncfinasset_yoy,
    FVTPL_FINASSET_YOY as fvtpl_finasset_yoy,
    FVTPL_FINLIAB_YOY as fvtpl_finliab_yoy,
    GENERAL_RISK_RESERVE_YOY as general_risk_reserve_yoy,
    GOODWILL_YOY as goodwill_yoy,
    HOLD_MATURITY_INVEST_YOY as hold_maturity_invest_yoy,
    HOLDSALE_ASSET_YOY as holdsale_asset_yoy,
    HOLDSALE_LIAB_YOY as holdsale_liab_yoy,
    INSURANCE_CONTRACT_RESERVE_YOY as insurance_contract_reserve_yoy,
    INTANGIBLE_ASSET_YOY as intangible_asset_yoy,
    INTEREST_PAYABLE_YOY as interest_payable_yoy,
    INTEREST_RECE_YOY as interest_rece_yoy,
    INTERNAL_PAYABLE_YOY as internal_payable_yoy,
    INTERNAL_RECE_YOY as internal_rece_yoy,
    INVENTORY_YOY as inventory_yoy,
    INVEST_REALESTATE_YOY as invest_realestate_yoy,
    LEASE_LIAB_YOY as lease_liab_yoy,
    LEND_FUND_YOY as lend_fund_yoy,
    LIAB_BALANCE_YOY as liab_balance_yoy,
    LIAB_EQUITY_BALANCE_YOY as liab_equity_balance_yoy,
    LIAB_EQUITY_OTHER_YOY as liab_equity_other_yoy,
    LIAB_OTHER_YOY as liab_other_yoy,
    LOAN_ADVANCE_YOY as loan_advance_yoy,
    LOAN_PBC_YOY as loan_pbc_yoy,
    LONG_EQUITY_INVEST_YOY as long_equity_invest_yoy,
    LONG_LOAN_YOY as long_loan_yoy,
    LONG_PAYABLE_YOY as long_payable_yoy,
    LONG_PREPAID_EXPENSE_YOY as long_prepaid_expense_yoy,
    LONG_RECE_YOY as long_rece_yoy,
    LONG_STAFFSALARY_PAYABLE_YOY as long_staffsalary_payable_yoy,
    MINORITY_EQUITY_YOY as minority_equity_yoy,
    MONETARYFUNDS_YOY as monetary_funds_yoy,
    NONCURRENT_ASSET_1YEAR_YOY as noncurrent_asset_1year_yoy,
    NONCURRENT_ASSET_BALANCE_YOY as noncurrent_asset_balance_yoy,
    NONCURRENT_ASSET_OTHER_YOY as noncurrent_asset_other_yoy,
    NONCURRENT_LIAB_1YEAR_YOY as noncurrent_liab_1year_yoy,
    NONCURRENT_LIAB_BALANCE_YOY as noncurrent_liab_balance_yoy,
    NONCURRENT_LIAB_OTHER_YOY as noncurrent_liab_other_yoy,
    NOTE_ACCOUNTS_PAYABLE_YOY as note_accounts_payable_yoy,
    NOTE_ACCOUNTS_RECE_YOY as note_accounts_rece_yoy,
    NOTE_PAYABLE_YOY as note_payable_yoy,
    NOTE_RECE_YOY as note_rece_yoy,
    OIL_GAS_ASSET_YOY as oil_gas_asset_yoy,
    OTHER_COMPRE_INCOME_YOY as other_compre_income_yoy,
    OTHER_CREDITOR_INVEST_YOY as other_creditor_invest_yoy,
    OTHER_CURRENT_ASSET_YOY as other_current_asset_yoy,
    OTHER_CURRENT_LIAB_YOY as other_current_liab_yoy,
    OTHER_EQUITY_INVEST_YOY as other_equity_invest_yoy,
    OTHER_EQUITY_OTHER_YOY as other_equity_other_yoy,
    OTHER_EQUITY_TOOL_YOY as other_equity_tool_yoy,
    OTHER_NONCURRENT_ASSET_YOY as other_noncurrent_asset_yoy,
    OTHER_NONCURRENT_FINASSET_YOY as other_noncurrent_finasset_yoy,
    OTHER_NONCURRENT_LIAB_YOY as other_noncurrent_liab_yoy,
    OTHER_PAYABLE_YOY as other_payable_yoy,
    OTHER_RECE_YOY as other_rece_yoy,
    PARENT_EQUITY_BALANCE_YOY as parent_equity_balance_yoy,
    PARENT_EQUITY_OTHER_YOY as parent_equity_other_yoy,
    PERPETUAL_BOND_PAYBALE_YOY as perpetual_bond_payable_yoy,
    PERPETUAL_BOND_YOY as perpetual_bond_yoy,
    PREDICT_CURRENT_LIAB_YOY as predict_current_liab_yoy,
    PREDICT_LIAB_YOY as predict_liab_yoy,
    PREFERRED_SHARES_PAYBALE_YOY as preferred_shares_payable_yoy,
    PREFERRED_SHARES_YOY as preferred_shares_yoy,
    PREMIUM_RECE_YOY as premium_rece_yoy,
    PREPAYMENT_YOY as prepayment_yoy,
    PRODUCTIVE_BIOLOGY_ASSET_YOY as productive_biology_asset_yoy,
    PROJECT_MATERIAL_YOY as project_material_yoy,
    RC_RESERVE_RECE_YOY as rc_reserve_rece_yoy,
    REINSURE_PAYABLE_YOY as reinsure_payable_yoy,
    REINSURE_RECE_YOY as reinsure_rece_yoy,
    SELL_REPO_FINASSET_YOY as sell_repo_finasset_yoy,
    SETTLE_EXCESS_RESERVE_YOY as settle_excess_reserve_yoy,
    SHARE_CAPITAL_YOY as share_capital_yoy,
    SHORT_BOND_PAYABLE_YOY as short_bond_payable_yoy,
    SHORT_FIN_PAYABLE_YOY as short_fin_payable_yoy,
    SHORT_LOAN_YOY as short_loan_yoy,
    SPECIAL_PAYABLE_YOY as special_payable_yoy,
    SPECIAL_RESERVE_YOY as special_reserve_yoy,
    STAFF_SALARY_PAYABLE_YOY as staff_salary_payable_yoy,
    SUBSIDY_RECE_YOY as subsidy_rece_yoy,
    SURPLUS_RESERVE_YOY as surplus_reserve_yoy,
    TAX_PAYABLE_YOY as tax_payable_yoy,
    TOTAL_ASSETS_YOY as total_assets_yoy,
    TOTAL_CURRENT_ASSETS_YOY as total_current_assets_yoy,
    TOTAL_CURRENT_LIAB_YOY as total_current_liab_yoy,
    TOTAL_EQUITY_YOY as total_equity_yoy,
    TOTAL_LIAB_EQUITY_YOY as total_liab_equity_yoy,
    TOTAL_LIABILITIES_YOY as total_liabilities_yoy,
    TOTAL_NONCURRENT_ASSETS_YOY as total_noncurrent_assets_yoy,
    TOTAL_NONCURRENT_LIAB_YOY as total_noncurrent_liab_yoy,
    TOTAL_OTHER_PAYABLE_YOY as total_other_payable_yoy,
    TOTAL_OTHER_RECE_YOY as total_other_rece_yoy,
    TOTAL_PARENT_EQUITY_YOY as total_parent_equity_yoy,
    TRADE_FINASSET_NOTFVTPL_YOY as trade_finasset_notfvtpl_yoy,
    TRADE_FINASSET_YOY as trade_finasset_yoy,
    TRADE_FINLIAB_NOTFVTPL_YOY as trade_finliab_notfvtpl_yoy,
    TRADE_FINLIAB_YOY as trade_finliab_yoy,
    TREASURY_SHARES_YOY as treasury_shares_yoy,
    UNASSIGN_RPOFIT_YOY as unassigned_profit_yoy,
    UNCONFIRM_INVEST_LOSS_YOY as unconfirm_invest_loss_yoy,
    USERIGHT_ASSET_YOY as use_right_asset_yoy,
    OPINION_TYPE as opinion_type,
    OSOPINION_TYPE as osopinion_type,
    LISTING_STATE as listing_state
from source
