#!/bin/sh
set -eu

clickhouse-client --host 127.0.0.1 --user "$CLICKHOUSE_USER" --password "$CLICKHOUSE_PASSWORD" --multiquery <<-EOSQL
CREATE DATABASE IF NOT EXISTS ${REARVIEW_CLICKHOUSE_MARTS_DATABASE:-fleur_marts};
CREATE DATABASE IF NOT EXISTS ${REARVIEW_CLICKHOUSE_PORTFOLIO_DATABASE:-fleur_portfolio};
CREATE DATABASE IF NOT EXISTS ${REARVIEW_CLICKHOUSE_CALCULATION_DATABASE:-fleur_calculation};
CREATE DATABASE IF NOT EXISTS fleur_backtest;
EOSQL
